--분기별 통계
--월별통계
--년도별 통계

SELECT * FROM PROFESSORS;
/*1970 ~ 1990년 년도별로 태어날 교수 숫자
1970 : 0
~~
1990 : 0
*/

SELECT PID, PNAME, BIRTH,
    SUBSTR(TRIM(BIRTH), 1, 4)
FROM PROFESSORS;

SELECT SUBSTR(TRIM(BIRTH), 1, 4), COUNT(*)
FROM PROFESSORS
GROUP BY SUBSTR(TRIM(BIRTH), 1, 4)
ORDER BY SUBSTR(TRIM(BIRTH), 1, 4) ASC
;

SELECT 1969 + LEVEL
FROM DUAL
CONNECT BY LEVEL <= 21
;


SELECT A.BSYEAR, NVL(B.CNT, 0) AS CNT FROM
(
    SELECT 1969 + LEVEL AS BSYEAR
    FROM DUAL
    CONNECT BY LEVEL <= 21
) A
,
(
    SELECT SUBSTR(TRIM(BIRTH), 1, 4) AS BIRTHYEAR , COUNT(*) AS CNT
    FROM PROFESSORS
    GROUP BY SUBSTR(TRIM(BIRTH), 1, 4)
    ORDER BY SUBSTR(TRIM(BIRTH), 1, 4) ASC
) B
WHERE A.BSYEAR = B.BIRTHYEAR(+)
ORDER BY A.BSYEAR ASC
;
