CREATE OR REPLACE 
PACKAGE PKG_REPLY_BOARD AS 

    PROCEDURE PROC_INS_BOARDS
    (
        IN_IDX      IN  VARCHAR2,
        IN_TITLE    IN  VARCHAR2,
        IN_CONTENT  IN  VARCHAR2,
        IN_USERID   IN  VARCHAR2,
        IN_REGNUM   IN  VARCHAR2,
        IN_LVL      IN  VARCHAR2,
        IN_COMBINE  IN  VARCHAR2,
        IN_LMENUID  IN  VARCHAR2,
        IN_ORD      IN  VARCHAR2
    );

END PKG_REPLY_BOARD;