CREATE OR REPLACE
PACKAGE BODY PKG_DOCTOR AS

-- INSERT
  PROCEDURE PROC_INS_DOCTOR
(
    IN_DOC_NAME     IN      VARCHAR2,
    IN_DOC_GENDER   IN      VARCHAR2,
    IN_HOS_ID       IN      VARCHAR2,
    IN_DOC_DEPT_GRP IN      VARCHAR2,
    IN_DOC_DEPT     IN      VARCHAR2,
    O_ERRCODE       OUT     VARCHAR2,
    O_ERRMSG        OUT     VARCHAR2  
)
 AS
 V_NEW_DOC_ID       CHAR(6);-- 신규생성ID
 V_CHK_DOC_ID       CHAR(1);-- 중복 체크
 DOCTOR_INS_EXCEPTION EXCEPTION;
  BEGIN
  
    SELECT DECODE(MAX(DOC_ID),NULL,0,1)
    INTO V_CHK_DOC_ID
    FROM DOCTOR_TBL 
    WHERE DOC_NAME = IN_DOC_NAME
    AND DOC_GENDER = IN_DOC_GENDER
    AND HOS_ID = IN_HOS_ID; 
    
    IF V_CHK_DOC_ID= 1 THEN
        RAISE DOCTOR_INS_EXCEPTION;
    ELSE
        SELECT 'DOC' || TO_CHAR(TO_NUMBER(SUBSTR(NVL(MAX(DOC_ID), 'DOC000'),4,3)) + 1, 'FM000') INTO V_NEW_DOC_ID FROM DOCTOR_TBL;
        INSERT INTO DOCTOR_TBL (DOC_ID, DOC_NAME, DOC_GENDER, HOS_ID, DOC_DEPT_GRP, DOC_DEPT)
        VALUES (V_NEW_DOC_ID, IN_DOC_NAME, IN_DOC_GENDER, IN_HOS_ID, IN_DOC_DEPT_GRP, IN_DOC_DEPT);
    END IF;
    
    EXCEPTION -- IF
    WHEN DOCTOR_INS_EXCEPTION THEN
    O_ERRCODE:= 'DOCTOR_ERR001';
    O_ERRMSG:= '이미 존재하는 ID입니다.';
  
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('입력한 데이터중 잘못된 정보가 있습니다!');
    O_ERRCODE:=SQLCODE;
    O_ERRMSG:=SQLERRM;
    
 
    
    
    
    
  END PROC_INS_DOCTOR;

-- SELECT
  PROCEDURE PROC_SEL_DOCTOR
(
    IN_DOC_ID     IN    VARCHAR2,
    IN_DOC_NAME   IN    VARCHAR2,   
    O_CUR         OUT   SYS_REFCURSOR,
    O_ERRCODE       OUT     VARCHAR2,
    O_ERRMSG        OUT     VARCHAR2   
)
 AS
  BEGIN
    OPEN O_CUR FOR
    SELECT * FROM DOCTOR_TBL
    WHERE DOC_ID LIKE '%'||IN_DOC_ID||'%'
    AND DOC_NAME LIKE'%'||IN_DOC_NAME||'%'
    ;

    EXCEPTION WHEN OTHERS THEN
      O_ERRCODE:=SQLCODE;
      O_ERRMSG:=SQLERRM;
  END PROC_SEL_DOCTOR;
  
  
-- UPDATE
  PROCEDURE PROC_UP_DOCTOR
(
    IN_DOC_ID       IN      VARCHAR2,
    IN_DOC_NAME     IN      VARCHAR2,
    IN_DOC_GENDER   IN      VARCHAR2,
    IN_HOS_ID       IN      VARCHAR2,
    IN_DOC_DEPT_GRP IN      VARCHAR2,
    IN_DOC_DEPT     IN      VARCHAR2,
    O_ERRCODE       OUT     VARCHAR2,
    O_ERRMSG        OUT     VARCHAR2
)
 AS
  BEGIN
  UPDATE DOCTOR_TBL
  SET DOC_ID       = IN_DOC_ID,
      DOC_NAME     = IN_DOC_NAME,
      DOC_GENDER   = IN_DOC_GENDER,
      HOS_ID       = IN_HOS_ID,
      DOC_DEPT_GRP = IN_DOC_DEPT_GRP,
      DOC_DEPT     = IN_DOC_DEPT
  WHERE DOC_ID = IN_DOC_ID;
      
    EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('입력한 데이터중 잘못된 정보가 있습니다!');
    O_ERRCODE:=SQLCODE;
    O_ERRMSG:=SQLERRM;
  
    
  END PROC_UP_DOCTOR;

-- DELETE
  PROCEDURE PROC_DEL_DOCTOR
(
    
    IN_DOC_ID       IN      VARCHAR2,
    O_ERRCODE       OUT     VARCHAR2,
    O_ERRMSG        OUT     VARCHAR2
)
 AS
    V_DOC_CNT NUMBER(2);
    DOCTOR_DEL_EXCEPTION EXCEPTION;
  BEGIN
  
      SELECT DECODE(MAX(DOC_ID),NULL,0,1)
      INTO V_DOC_CNT 
      FROM DOCTOR_TBL 
      WHERE DOC_ID=IN_DOC_ID;
      IF V_DOC_CNT=0 THEN
        RAISE DOCTOR_DEL_EXCEPTION; -- 오류 실행 
      ELSE
        DELETE FROM DOCTOR_TBL WHERE DOC_ID=IN_DOC_ID;
      END IF;
      
      EXCEPTION WHEN DOCTOR_DEL_EXCEPTION THEN
      O_ERRCODE:='DOCTOR_ERR004';
      O_ERRMSG:='지우려는 DOCTOR DATA가 존재하지 않습니다';
      
      WHEN OTHERS THEN
      O_ERRCODE:=SQLCODE;
      O_ERRMSG:=SQLERRM;
      
    
  END PROC_DEL_DOCTOR;

END PKG_DOCTOR;