CREATE TABLE BOARDS
(
    IDX     INT     PRIMARY KEY,
    TITLE   VARCHAR2(200)   NOT NULL,
    USERID  CHAR(6)   NOT NULL
);

CREATE TABLE MEMBERS
(
    USERID  CHAR(6) PRIMARY KEY,
    USERNAME    VARCHAR2(100)   NOT NULL
);

INSERT INTO MEMBERS(USERID, USERNAME) VALUES('USER01', 'DITTO');
INSERT INTO MEMBERS(USERID, USERNAME) VALUES('USER02', 'MARSH');
INSERT INTO MEMBERS(USERID, USERNAME) VALUES('USER03', 'WAN');
INSERT INTO MEMBERS(USERID, USERNAME) VALUES('USER04', 'METAMON');
INSERT INTO MEMBERS(USERID, USERNAME) VALUES('USER05', 'OCTO');

INSERT INTO BOARDS(IDX, TITLE, USERID) VALUES(1, 'YOONA IS BABO', 'USER03');
INSERT INTO BOARDS(IDX, TITLE, USERID) VALUES(2, 'YOONA IS GONE', 'USER02');
INSERT INTO BOARDS(IDX, TITLE, USERID) VALUES(3, 'PATIENT YOONA', 'USER05');

