CREATE OR REPLACE 
PACKAGE PKG_TESTTBL AS 

  PROCEDURE PROC_TESTTBL
  (
    IN_GBN1     IN      VARCHAR2,
    IN_GBN2     IN      VARCHAR2,
    O_CUR       OUT     SYS_REFCURSOR,
    O_VAL       OUT     VARCHAR2
  );

END PKG_TESTTBL;