CREATE TABLE TESTTBL
(
    FID     CHAR(4)     PRIMARY KEY,
    FNAME   VARCHAR2(100)   NOT NULL,
    GBN1    CHAR(1)         NOT NULL,
    GBN2    CHAR(2)         NOT NULL
);


INSERT INTO TESTTBL VALUES('F001', '진로', 'A', '1');
INSERT INTO TESTTBL VALUES('F002', '참이슬', 'A', '1');
INSERT INTO TESTTBL VALUES('F003', '좋은데이', 'A', '1');
INSERT INTO TESTTBL VALUES('F004', '처음처럼', 'A', '1');

INSERT INTO TESTTBL VALUES('F005', '카스', 'A', '2');
INSERT INTO TESTTBL VALUES('F006', '테라', 'A', '2');
INSERT INTO TESTTBL VALUES('F007', '필라이트', 'A', '2');
INSERT INTO TESTTBL VALUES('F008', '클라우드', 'A', '2');

INSERT INTO TESTTBL VALUES('F009', '보드카', 'A', '3');
INSERT INTO TESTTBL VALUES('F010', '진', 'A', '3');
INSERT INTO TESTTBL VALUES('F011', '예거마이스터', 'A', '3');
INSERT INTO TESTTBL VALUES('F012', '깔루아', 'A', '3');

INSERT INTO TESTTBL VALUES('F013', '치킨', 'B', '1');
INSERT INTO TESTTBL VALUES('F014', '피자', 'B', '1');
INSERT INTO TESTTBL VALUES('F015', '햄버거', 'B', '1');
INSERT INTO TESTTBL VALUES('F016', '족발', 'B', '1');

INSERT INTO TESTTBL VALUES('F017', '참치', 'B', '2');
INSERT INTO TESTTBL VALUES('F018', '연어', 'B', '2');
INSERT INTO TESTTBL VALUES('F019', '광어', 'B', '2');
INSERT INTO TESTTBL VALUES('F020', '농어', 'B', '2');

INSERT INTO TESTTBL VALUES('F021', '팝콘', 'B', '3');
INSERT INTO TESTTBL VALUES('F022', '치토스', 'B', '3');
INSERT INTO TESTTBL VALUES('F023', '콘칩', 'B', '3');
INSERT INTO TESTTBL VALUES('F024', '포카칩', 'B', '3');

INSERT INTO TESTTBL VALUES('F025', '아메리카노', 'C', '1');
INSERT INTO TESTTBL VALUES('F026', '에스프레소', 'C', '1');
INSERT INTO TESTTBL VALUES('F027', '카페라떼', 'C', '1');
INSERT INTO TESTTBL VALUES('F028', '카페모카', 'C', '1');

INSERT INTO TESTTBL VALUES('F029', '녹차라떼', 'C', '2');
INSERT INTO TESTTBL VALUES('F030', '딸기라떼', 'C', '2');
INSERT INTO TESTTBL VALUES('F031', '바닐라빈라떼', 'C', '2');
INSERT INTO TESTTBL VALUES('F032', '고구마라떼', 'C', '2');

INSERT INTO TESTTBL VALUES('F033', '마카롱', 'C', '3');
INSERT INTO TESTTBL VALUES('F034', '크로플', 'C', '3');
INSERT INTO TESTTBL VALUES('F035', '쿠키', 'C', '3');
INSERT INTO TESTTBL VALUES('F036', '와플', 'C', '3');

INSERT INTO TESTTBL VALUES('F037', 'JAVA', 'D', '1');
INSERT INTO TESTTBL VALUES('F038', 'PYTHON', 'D', '1');
INSERT INTO TESTTBL VALUES('F039', 'C#', 'D', '1');
INSERT INTO TESTTBL VALUES('F040', 'C++', 'D', '1');

INSERT INTO TESTTBL VALUES('F041', 'ORACLE', 'D', '2');
INSERT INTO TESTTBL VALUES('F042', 'MYSQL', 'D', '2');
INSERT INTO TESTTBL VALUES('F043', 'MONGODB', 'D', '2');
INSERT INTO TESTTBL VALUES('F044', 'MARIADB', 'D', '2');

INSERT INTO TESTTBL VALUES('F045', 'SPRING', 'D', '3');
INSERT INTO TESTTBL VALUES('F046', 'DJANGO', 'D', '3');
INSERT INTO TESTTBL VALUES('F047', 'REACT', 'D', '3');
INSERT INTO TESTTBL VALUES('F048', 'VUE', 'D', '3');


