--날짜함수 -- 엔진은 숫자로 받아들여요 -- DATA 타입
SELECT SYSDATE + 5 FROM DUAL;   -->DATE
SELECT SYSDATE - SYSDATE FROM DUAL;  --> 숫자


SELECT * FROM STUDENTS;
SELECT * FROM PROFESSORS;

--각교별로 나이 한번 구해보자
SELECT SYSDATE - TO_DATE('19970501') FROM DUAL;


--날짜 함수
--1. TO_DATE : 다른 데이터타입을 날짜타입으로 변환하려고 만든함수
SELECT TO_DATE('1999*12*14', 'YYYY-MM-DD') FROM DUAL;
SELECT TO_DATE(99999999, 'YYYY-MM-DD') FROM DUAL;

--2. 날짜를 빼고 더할때
SELECT TO_NUMBER('19551101') + 45 FROM DUAL; --19551101 + 45 ??
SELECT TO_DATE('19551101') + 45 FROM DUAL;  --1955년 11월 1일 부터 45일 뒤가 몇일이니??
--19250708 인데 19500625에는 몇일이나 살았니
SELECT 19500625 - 19250708 FROM DUAL;  -- 두수의 계산
SELECT TO_DATE(19500625, 'YYYYMMDD') - TO_DATE(19250708, 'YYYYMMDD') FROM DUAL;

-- DATE 함수 함수명이 DAY가 붙어있으면 요일을 구하는 함수
--1.3 ADD_MONTHS();
SELECT BIRTH, ADD_MONTHS(TO_DATE(BIRTH, 'YYYYMMDD'), -7) FROM PROFESSORS;
SELECT BIRTH, ADD_MONTHS(TO_DATE(BIRTH, 'YYYYMMDD'), 9) FROM PROFESSORS;


--1.4 CURRENT_DATE();
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS'), 
       TO_CHAR(CURRENT_DATE, 'YYYY-MM-DD HH:MI:SS')  -- 트랜잭션...
FROM DUAL;

--1.5 LAST_DAY() -- 주어진값에 해당달의 마지막날을 보여줍니다.
SELECT BIRTH, LAST_DAY(TO_DATE(BIRTH, 'YYYYMMDD')) FROM PROFESSORS;
SELECT BIRTH, LAST_DAY(BIRTH) FROM PROFESSORS;

--1.6 MONTHS_BETWEEN 함수
SELECT TRUNC(MONTHS_BETWEEN('20220201','20220112'), 0) FROM DUAL;

--1.7 TRUNC - 예제가 필요

--TO_CHAR
SELECT TO_CHAR(SYSDATE) FROM DUAL;  --데이터타입 변환
SELECT TO_CHAR(SYSDATE, 'YYYY') || '년 ' || 
       TO_CHAR(SYSDATE, 'MM')   || '월 ' ||
       TO_CHAR(SYSDATE, 'MM')   || '일'
FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'MM') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'HH') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'HH24') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'MI') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'SS') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'HH:MI:SS') FROM DUAL;

SELECT * FROM PROFESSORS;
--교수의 나이를 구해보자 -- 우리나라나이
SELECT BIRTH, SUBSTR(BIRTH, 1, 4) AS BIRTHYEAR, SUBSTR(SYSDATE, 1, 4) NOWYEAR,
TO_CHAR(SYSDATE, 'YYYY'), TO_CHAR(SYSDATE, 'YYYY') - SUBSTR(BIRTH, 1, 4) + 1 AS PAGE
FROM PROFESSORS;

