    SELECT 
        LPAD(' ', 2*(LEVEL-1)) || MENUNAME AS MENUNAME,
        MENUSEQ, MENULVL, MENUID, PARENTID
    FROM MENUS
    START WITH PARENTID = 'ROOT'
    CONNECT BY PRIOR MENUID = PARENTID
    ;




SELECT * FROM
(
    SELECT 
        LPAD(' ', 2*(LEVEL-1)) || MENUNAME AS MENUNAME,
        MENUSEQ, MENULVL, MENUID, PARENTID
    FROM MENUS
    START WITH PARENTID = 'ROOT'
    CONNECT BY PRIOR MENUID = PARENTID
) T1
,
(
    SELECT T5.MENUID, T5.PID, T5.PFILENAME
    FROM MENUS T1, MENUS T2, MENUS T3, MENUS T4, PROGRAMS T5
    WHERE T1.MENUID = T2.PARENTID(+)
    AND T2.MENUID = T3.PARENTID(+)
    AND T3.MENUID = T4.PARENTID(+)
    AND (T2.MENUID = T5.MENUID OR T3.MENUID = T5.MENUID OR T4.MENUID = T5.MENUID)
    AND T1.MENULVL = 1
    ORDER BY T1.MENUID, T2.MENUID, T3.MENUID, T4.MENUID
) T2
WHERE T1.MENUID = T2.MENUID(+)
;


SELECT T1.MENUID, T1.MENUNAME, T1.MENUSEQ, T1.MENULVL, T1.PARENTID,
       T2.PID, T2.PFILENAME
FROM
(
    SELECT 
        LPAD(' ', 2*(LEVEL-1)) || MENUNAME AS MENUNAME,
        MENUSEQ, MENULVL, MENUID, PARENTID
    FROM MENUS
    START WITH PARENTID = 'ROOT'
    CONNECT BY PRIOR MENUID = PARENTID
) T1
,
(
    SELECT T5.MENUID, T5.PID, T5.PFILENAME
    FROM MENUS T1, MENUS T2, MENUS T3, MENUS T4, PROGRAMS T5
    WHERE T1.MENUID = T2.PARENTID(+)
    AND T2.MENUID = T3.PARENTID(+)
    AND T3.MENUID = T4.PARENTID(+)
    AND (T2.MENUID = T5.MENUID OR T3.MENUID = T5.MENUID OR T4.MENUID = T5.MENUID)
    AND T1.MENULVL = 1
    ORDER BY T1.MENUID, T2.MENUID, T3.MENUID, T4.MENUID
) T2
,
(
    SELECT * FROM AUTH_MENUS
    WHERE AUTHID = 'AUTH001'
) T3
WHERE T1.MENUID = T2.MENUID(+)
AND T1.MENUID = T3.MENUID(+)
;



