--1. 회원
CREATE TABLE MEMBERS
(
    MID         CHAR(7)         NOT NULL PRIMARY KEY,
    MNAME       VARCHAR2(30)    NOT NULL
);

INSERT INTO MEMBERS VALUES('M000001','홍길동');
INSERT INTO MEMBERS VALUES('M000002','전우치');
INSERT INTO MEMBERS VALUES('M000003','신데렐라');
INSERT INTO MEMBERS VALUES('M000004','백설공주');
INSERT INTO MEMBERS VALUES('M000005','괴도루팡');

--COMMIT;