
--PROCEDURE

SELECT * FROM STUDENTS_TBL;
SELECT * FROM STUDENTS_TIME_TBL;

--2018년 2월 2일부터 3일까지 수강신청한 학생 명단
SELECT T1.STU_ID, T1.STU_NAME
FROM STUDENTS_TBL T1, STUDENTS_TIME_TBL T2
WHERE T1.STU_ID=T2.STU_ID
    AND TO_CHAR(T2.REG_TIME, 'YYYYMMDD') >= '20180202'
    AND TO_CHAR(T2.REG_TIME, 'YYYYMMDD') <= '20180203'
GROUP BY T1.STU_ID, T1.STU_NAME
;


--이름으로 수강신청한 과목 조회
SELECT T1.STU_ID, T1.STU_NAME, T3.SUB_ID, T3.SUB_NAME
FROM STUDENTS_TBL T1, STUDENTS_TIME_TBL T2, SUBJECTS_TBL T3
WHERE T1.STU_ID=T2.STU_ID
    AND T2.SUB_ID=T3.SUB_ID
    AND T1.STU_NAME LIKE '%'||:IN_STU_NAME||'%'
;


---------------
CREATE TABLE BOARDS
(
    IDX     INTEGER         PRIMARY KEY,
    TITLE   VARCHAR2(300)   NOT NULL,
    CONTENT VARCHAR2(4000)  NOT NULL,
    REGDATE DATE            NOT NULL
);
SELECT * FROM BOARDS;
--글쓰기(INSERT)
INSERT INTO BOARDS(IDX, TITLE, CONTENT, REGDATE)
VALUES (1, '안녕하세요','ㅁㄴㅇㄹㄴㅇㄻㄴㄹㅇ',SYSDATE);
INSERT INTO BOARDS(IDX, TITLE, CONTENT, REGDATE)
VALUES (2, '어서오세요','ㅋㅌㅊㅍㅌㅋㅊㅍ',SYSDATE);
--COMMIT
--게시판에 글 작성 시 위와 같은 내용이 계속 반복

--아래와 같은 내용들도 반복된다
--글수정(UPDATE)
UPDATE BOARDS
SET TITLE=:IN_TITLE, CONTENT=:IN_CONTENT, REGDATE=SYSDATE
WHERE IDX=:IN_IDX
;

--글삭제(DELETE)
DELETE FROM BOARDS WHERE IDX=:IN_IDX
;

--글 조회(SELECT)
SELECT *
FROM BOARDS
WHERE TITLE LIKE '%'||:IN_TITLE||'%'
ORDER BY IDX DESC
;

--PROCEDURE로 만들면?
    --글쓰기, 수정, 삭제 등 관련 PROCEDURE들이 많이 생긴다
    --PROCEDURE를 묶어서 관련된 내용들끼리 정리 : PACKAGE

--CRUD
--입력 INSERT : CREATE
--조회 SELECT : RETRIVE
--수정 UPDATE : UPDATE
--삭제 DELETE : DELETE

------------------------------------
--학생이 게시판에 글을 작성(1대 다)
SELECT * FROM BOARDS;
SELECT * FROM STUDENTS_TBL;



------------------------
SELECT * FROM PROFESSORS_TBL;
--교수추가
INSERT INTO PROFESSORS_TBL(PRO_ID, PRO_NAME, PRO_ADDR_GRP, PRO_ADDR, PRO_ADDR2, PRO_DEPT_GRP, PRO_DEPT)
VALUES('PRO041', '강도우', 'GRP001','COM0033', 'COM0002','GRP002','COM0016');

--조회
SELECT * FROM PROFESSORS_TBL
WHERE PRO_ID LIKE '%'||:IN_PRO_ID||'%'
    AND PRO_NAME LIKE '%'||:IN_PRO_NAME||'%'
;

--수정
UPDATE PROFESSORS_TBL
SET PRO_NAME=:IN_PRO_NAME,
    PRO_ADDR_GRP=:IN_PRO_ADDR_GRP,
    PRO_ADDR=:IN_PRO_ADDR,
    PRO_ADDR2=:IN_PRO_ADDR2,
    PRO_DEPT_GRP=:IN_PRO_DEPT_GRP,
    PRO_DEPT=:IN_PRO_DEPT
WHERE PRO_ID=:IN_PRO_ID
;

--삭제
DELETE FROM PROFESSORS_TBL
WHERE PRO_ID=:IN_PRO_ID
;

---------------------

--수강신청 테이블의 CRUD 해보기 + 패키지만들기
SELECT * FROM STUDENTS_TIME_TBL;

