/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-27 05:55:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.boards;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import pkg.boards.VO.MemberVO;
import pkg.boards.VO.BoardVO;
import java.util.ArrayList;

public final class boards_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("pkg.boards.VO.MemberVO");
    _jspx_imports_classes.add("pkg.boards.VO.BoardVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("  integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Boards</title>\r\n");

	ArrayList<BoardVO> boardList = (ArrayList<BoardVO>)request.getAttribute("boardList");
	ArrayList<MemberVO> memberList = (ArrayList<MemberVO>)request.getAttribute("memberList");

      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	.bRow{\r\n");
      out.write("		width:510px;\r\n");
      out.write("		height:30px;\r\n");
      out.write("		border:0px solid #777;\r\n");
      out.write("		clear:both;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.col1{\r\n");
      out.write("		width:50px;\r\n");
      out.write("		font-size:12px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		padding:8px 0px 5px 0px;\r\n");
      out.write("		border:1px solid #999;\r\n");
      out.write("		display:block;\r\n");
      out.write("		float:left;\r\n");
      out.write("	}\r\n");
      out.write("	.col2{\r\n");
      out.write("		width:90px;\r\n");
      out.write("		font-size:12px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		padding:8px 0px 5px 0px;\r\n");
      out.write("		border:1px solid #999;\r\n");
      out.write("		display:block;\r\n");
      out.write("		float:left;\r\n");
      out.write("	}\r\n");
      out.write("	.col3{\r\n");
      out.write("		width:200px;\r\n");
      out.write("		font-size:12px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		padding:8px 0px 5px 0px;\r\n");
      out.write("		border:1px solid #999;\r\n");
      out.write("		display:block;\r\n");
      out.write("		float:left;\r\n");
      out.write("	}\r\n");
      out.write("	.col4{\r\n");
      out.write("		width:130px;\r\n");
      out.write("		font-size:12px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		padding:8px 0px 5px 0px;\r\n");
      out.write("		border:1px solid #999;\r\n");
      out.write("		display:block;\r\n");
      out.write("		float:left;\r\n");
      out.write("	}\r\n");
      out.write("	.col5{\r\n");
      out.write("		width:30px;\r\n");
      out.write("		font-size:12px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		padding:8px 0px 5px 0px;\r\n");
      out.write("		border:1px solid #999;\r\n");
      out.write("		display:block;\r\n");
      out.write("		float:left;\r\n");
      out.write("	}\r\n");
      out.write("	input:focus{\r\n");
      out.write("		outline:none;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"jscss/css/test.css\"/> -->\r\n");
      out.write("<script src=\"jscss/js/commons.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		chkTitle2();\r\n");
      out.write("		addRowFunc();\r\n");
      out.write("		saveFunc();\r\n");
      out.write("		delFunc();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	var chkTitle = function(idx){\r\n");
      out.write("		var objStatus = document.getElementsByName(\"status\");\r\n");
      out.write("		objStatus[idx].value = \"u\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var chkTitle2 = function(){\r\n");
      out.write("		$(\"input[name='title2']\").change(function(){\r\n");
      out.write("			var chgIdx = $(\"input[name='title2']\").index(this);\r\n");
      out.write("			$(\"input[name='status2']\").eq(chgIdx).val(\"u\");\r\n");
      out.write("			//boardContent 밑의 idx번째 boardRow\r\n");
      out.write("			$(\"#boardContent2\").children().eq(chgIdx).css(\"background-color\",\"#BBB\");\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var addRowFunc = function(){\r\n");
      out.write("		$(\"#btnAdd2\").on(\"click\",function(){\r\n");
      out.write("			var strHTML = \"\";\r\n");
      out.write("			strHTML += '<div id=\"boardRow2\" class=\"bRow\">';\r\n");
      out.write("			strHTML += '<span class=\"col1\">';\r\n");
      out.write("			strHTML += '<input type=\"checkbox\" name=\"chk2\"/>';\r\n");
      out.write("			strHTML += '</span>';\r\n");
      out.write("			strHTML += '<span class=\"col2\">';\r\n");
      out.write("			strHTML += '<input type=\"text\" name=\"idx2\" style=\"border:none;width:50px;background-color:transparent\" value=\"\" /> </span>';\r\n");
      out.write("			strHTML += '<span class=\"col3\">';\r\n");
      out.write("			strHTML += '<input type=\"text\" name=\"title2\" style=\"border:none;width:auto;background-color:transparent\" value=\"\"/></span>';\r\n");
      out.write("			strHTML += '<span class=\"col4\">';\r\n");
      out.write("			strHTML += '<select name=\"userID2\">';\r\n");
      out.write("			strHTML += '");
 for(MemberVO mem : memberList){ 
      out.write("';\r\n");
      out.write("				strHTML += '<option value=\"");
      out.print(mem.getUserID());
      out.write("\"';\r\n");
      out.write("				");
 if(memberList.indexOf(mem)==0){ 
      out.write("\r\n");
      out.write("					strHTML += 'selected=\"selected\"';\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("				strHTML += '>';\r\n");
      out.write("				strHTML += '");
      out.print(mem.getUserName());
      out.write("</option>';\r\n");
      out.write("			strHTML += '");
 } 
      out.write("';\r\n");
      out.write("			strHTML += '</select>';\r\n");
      out.write("			strHTML += '</span>';\r\n");
      out.write("			strHTML += '<span class=\"col5\">';\r\n");
      out.write("			strHTML += '<input type=\"text\" name=\"status2\" style=\"border:none;width:10px;background-color:transparent\" value=\"i\" readonly/>';\r\n");
      out.write("			strHTML += '</span>';\r\n");
      out.write("			strHTML += '</div>';\r\n");
      out.write("			\r\n");
      out.write("			$(\"#boardContent2\").append(strHTML);\r\n");
      out.write("			$(\"#boardContent2\").children().last().css(\"background-color\",\"#BBB\");\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var saveFunc = function(){\r\n");
      out.write("		$(\"#btnSave2\").on(\"click\",function(){\r\n");
      out.write("			$(\"#boardForm\").attr(\"action\",\"saveBoard\");\r\n");
      out.write("			$(\"#boardForm\").submit();\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var delChk = function(){\r\n");
      out.write("		var delHTML = '';\r\n");
      out.write("		$(\"input[name='chk2']\").each(function(){\r\n");
      out.write("			if($(this).is(\":checked\")){\r\n");
      out.write("				delHTML += '<input type=\"hidden\" name=\"delIdx\" value=\"'+$(this).val()+'\"/>';\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#delDiv\").html(delHTML);\r\n");
      out.write("		$(\"#delForm\").attr(\"action\",\"deleteBoard\");\r\n");
      out.write("		$(\"#delForm\").submit();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var delFunc = function(){\r\n");
      out.write("		$(\"#btnDelete2\").on(\"click\",delChk);\r\n");
      out.write("		/*\r\n");
      out.write("		var formID = \"delForm\";\r\n");
      out.write("		var formAction = \"deleteBoard\";\r\n");
      out.write("		var formMethod = \"post\";\r\n");
      out.write("		var formNames = [];\r\n");
      out.write("		var formVals = [];\r\n");
      out.write("		\r\n");
      out.write("		$(\"input[name='chk']\").each(function(){\r\n");
      out.write("			if($(this).is(\":checked\")){\r\n");
      out.write("				formVals[i] = $(this).val();\r\n");
      out.write("				formNames[i] = \"delChk\";\r\n");
      out.write("				i++;\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		var submitObj = new objectSubmit(formID,formAction,formMethod,formNames,formVals);\r\n");
      out.write("		submitObj.linkSubmit()\r\n");
      out.write("		*/\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- javascript -->\r\n");
      out.write("<div style=\"clear:both\">---javascript---</div>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("	<input type=\"button\" value=\"조회\" id=\"btnSearch\" />\r\n");
      out.write("	<input type=\"button\" value=\"추가\" id=\"btnAdd\" />\r\n");
      out.write("	<input type=\"button\" value=\"저장\" id=\"btnSave\" />\r\n");
      out.write("	<input type=\"button\" value=\"삭제\" id=\"btnDelete\" />\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"board\">\r\n");
      out.write("	<div id=\"boardTitle\" class=\"bRow\">\r\n");
      out.write("		<span class=\"col1\">\r\n");
      out.write("			<input type=\"checkbox\" name=\"chk\"/>\r\n");
      out.write("		</span>\r\n");
      out.write("		<span class=\"col2\">글번호</span>\r\n");
      out.write("		<span class=\"col3\">글제목</span>\r\n");
      out.write("		<span class=\"col4\">작성자</span>\r\n");
      out.write("		<span class=\"col5\" style=\"visibility:hidden\">&nbsp;</span>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"boardContent\">\r\n");
      out.write("	");
 for(BoardVO vo : boardList){ 
      out.write("\r\n");
      out.write("	<div id=\"boardRow\" class=\"bRow\">\r\n");
      out.write("		<span class=\"col1\">\r\n");
      out.write("			<input type=\"checkbox\" name=\"chk\" value=\"");
      out.print(vo.getIdx() );
      out.write("\"/>\r\n");
      out.write("		</span>\r\n");
      out.write("		<span class=\"col2\">\r\n");
      out.write("			<input type=\"text\" name=\"idx\" style=\"border:none;width:50px;background-color:transparent\" value=\"");
      out.print(vo.getIdx() );
      out.write("\" /></span>\r\n");
      out.write("		<span class=\"col3\">\r\n");
      out.write("			<input type=\"text\" name=\"title\" style=\"border:none;width:auto;background-color:transparent\" value=\"");
      out.print(vo.getTitle() );
      out.write("\" onchange=\"chkTitle(");
      out.print(vo.getIdx() );
      out.write(")\"/></span>\r\n");
      out.write("		<span class=\"col4\">\r\n");
      out.write("			<select name=\"userID\">\r\n");
      out.write("			");
 for(MemberVO mem : memberList){ 
      out.write("\r\n");
      out.write("				<option value=\"");
      out.print(mem.getUserID());
      out.write("\"\r\n");
      out.write("					");
if(vo.getUserID().equals(mem.getUserID())){
      out.write("\r\n");
      out.write("					 selected=\"selected\"\r\n");
      out.write("					");
 } 
      out.write("	\r\n");
      out.write("				>");
      out.print(mem.getUserName());
      out.write("</option>\r\n");
      out.write("			");
 } 
      out.write("	\r\n");
      out.write("			</select>\r\n");
      out.write("		</span>\r\n");
      out.write("		<span class=\"col5\" style=\"visibility:hidden\">\r\n");
      out.write("			<input type=\"text\" name=\"status\" style=\"border:none;width:10px;background-color:transparent\" value=\"\" readonly/>\r\n");
      out.write("		</span>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<div style=\"clear:both\">---jquery---</div>\r\n");
      out.write("\r\n");
      out.write("<form name=\"boardForm\" id=\"boardForm\" method=\"post\">\r\n");
      out.write("<div>\r\n");
      out.write("	<input type=\"button\" value=\"조회\" id=\"btnSearch2\" />\r\n");
      out.write("	<input type=\"button\" value=\"추가\" id=\"btnAdd2\" />\r\n");
      out.write("	<input type=\"button\" value=\"저장\" id=\"btnSave2\" />\r\n");
      out.write("	<input type=\"button\" value=\"삭제\" id=\"btnDelete2\" />\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"board2\">\r\n");
      out.write("	<div id=\"boardTitle2\" class=\"bRow\">\r\n");
      out.write("		<span class=\"col1\">\r\n");
      out.write("			<input type=\"checkbox\" name=\"chk2\"/>\r\n");
      out.write("		</span>\r\n");
      out.write("		<span class=\"col2\">글번호</span>\r\n");
      out.write("		<span class=\"col3\">글제목</span>\r\n");
      out.write("		<span class=\"col4\">작성자</span>\r\n");
      out.write("		<span class=\"col5\" style=\"visibility:hidden\">&nbsp;</span>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"boardContent2\">\r\n");
      out.write("	");
 for(BoardVO vo : boardList){ 
      out.write("\r\n");
      out.write("	<div id=\"boardRow2\" class=\"bRow\">\r\n");
      out.write("		<span class=\"col1\">\r\n");
      out.write("			<input type=\"checkbox\" name=\"chk2\" value=\"");
      out.print(vo.getIdx() );
      out.write("\"/>\r\n");
      out.write("		</span>\r\n");
      out.write("		<span class=\"col2\">\r\n");
      out.write("			<input type=\"text\" name=\"idx2\" style=\"border:none;width:50px;background-color:transparent\" value=\"");
      out.print(vo.getIdx() );
      out.write("\" /></span>\r\n");
      out.write("		<span class=\"col3\">\r\n");
      out.write("			<input type=\"text\" name=\"title2\" style=\"border:none;width:auto;background-color:transparent\" value=\"");
      out.print(vo.getTitle() );
      out.write("\"/></span>\r\n");
      out.write("		<span class=\"col4\">\r\n");
      out.write("			<select name=\"userID2\">\r\n");
      out.write("			");
 for(MemberVO mem : memberList){ 
      out.write("\r\n");
      out.write("				<option value=\"");
      out.print(mem.getUserID());
      out.write("\"\r\n");
      out.write("					");
if(vo.getUserID().equals(mem.getUserID())){
      out.write("\r\n");
      out.write("					 selected=\"selected\"\r\n");
      out.write("					");
 } 
      out.write("	\r\n");
      out.write("				 >");
      out.print(mem.getUserName());
      out.write("</option>\r\n");
      out.write("			");
 } 
      out.write("	\r\n");
      out.write("			</select>\r\n");
      out.write("		</span>\r\n");
      out.write("		<span class=\"col5\" style=\"visibility:hidden\">\r\n");
      out.write("			<input type=\"text\" name=\"status2\" style=\"border:none;width:10px;background-color:transparent\" value=\"\" readonly/>\r\n");
      out.write("		</span>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("<form id=\"delForm\" name=\"delForm\" id=\"\" method=\"post\">\r\n");
      out.write("<div id=\"delDiv\"></div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
