

--drop table boards;
--대메뉴테이블
CREATE TABLE HMENUS
(
    MENUID      CHAR(6)         PRIMARY KEY,
    MENUNAME    VARCHAR2(50)    NOT NULL
);

CREATE TABLE LMENUS
(
    LMENUID     CHAR(6)         PRIMARY KEY,
    LMENUNAME   VARCHAR2(50)    NOT NULL,
    LMENUURL    VARCHAR2(100)   NOT NULL,
    MENUID      CHAR(6)         NOT NULL
);

CREATE TABLE BOARDS
(
    IDX         INT             PRIMARY KEY,
    TITLE       VARCHAR2(300)   NOT NULL,
    CONTENT     VARCHAR2(4000)  NOT NULL,
    USERID      VARCHAR2(20)    NOT NULL,
    REGNUM      INT             NOT NULL, -- DB에 쌓이는 순서?
    LVL         INT             NOT NULL, --글/답글 수준 조절
    COMBINE     INT             NOT NULL, --그룹?
    VISITED     INT             NOT NULL,
    REGDATE     DATE            NOT NULL,
    LMENUID     CHAR(6)         NOT NULL,
    ORD         INT             NOT NULL,
    DELNUM      INT             NOT NULL
);

CREATE TABLE REPLY
(
    IDX         INT             PRIMARY KEY,
    CONTENT     VARCHAR2(4000)  NOT NULL,
    USERID      VARCHAR2(30)    NOT NULL,
    REGDATE     DATE            NOT NULL,
    BIDX        INT             NOT NULL
);

/*
CREATE TABLE MEMBERS
(
    USERID      VARCHAR2(20)    PRIMARY KEY,
    USERPASS    VARCHAR2(20)    NOT NULL,
    USERNAME    VARCHAR2(30)    NOT NULL,
    USERGEN     CHAR(1)         NOT NULL,
    USERHOBBY   VARCHAR2(100)   NOT NULL,
    REGDATE     DATE            NOT NULL
);
*/



INSERT INTO MEMBERS(USERID, USERPASS, USERNAME, USERGEN, USERHOBBY, REGDATE)
VALUES('ADMIN','1111','WAN','M','P S ', SYSDATE);


INSERT INTO HMENUS(MENUID, MENUNAME) VALUES('MENU01','공지사항');
INSERT INTO HMENUS(MENUID, MENUNAME) VALUES('MENU02','공부');
INSERT INTO HMENUS(MENUID, MENUNAME) VALUES('MENU03','운동');
INSERT INTO HMENUS(MENUID, MENUNAME) VALUES('MENU04','코딩');
INSERT INTO HMENUS(MENUID, MENUNAME) VALUES('MENU05','자유게시판');


INSERT INTO LMENUS(LMENUID, LMENUNAME, LMENUURL, MENUID) VALUES('MENU01','공지',' ','MENU01');
INSERT INTO LMENUS(LMENUID, LMENUNAME, LMENUURL, MENUID) VALUES('MENU02','PM게시판',' ','MENU01');

INSERT INTO LMENUS(LMENUID, LMENUNAME, LMENUURL, MENUID) VALUES('MENU03','정보처리기사',' ','MENU02');
INSERT INTO LMENUS(LMENUID, LMENUNAME, LMENUURL, MENUID) VALUES('MENU04','SQLD',' ','MENU02');
INSERT INTO LMENUS(LMENUID, LMENUNAME, LMENUURL, MENUID) VALUES('MENU05','알고리즘',' ','MENU02');

INSERT INTO LMENUS(LMENUID, LMENUNAME, LMENUURL, MENUID) VALUES('MENU06','복싱',' ','MENU03');
INSERT INTO LMENUS(LMENUID, LMENUNAME, LMENUURL, MENUID) VALUES('MENU07','주짓수',' ','MENU03');
INSERT INTO LMENUS(LMENUID, LMENUNAME, LMENUURL, MENUID) VALUES('MENU08','스쿼시',' ','MENU03');

INSERT INTO LMENUS(LMENUID, LMENUNAME, LMENUURL, MENUID) VALUES('MENU09','FRONTEND',' ','MENU04');
INSERT INTO LMENUS(LMENUID, LMENUNAME, LMENUURL, MENUID) VALUES('MENU10','JAVA',' ','MENU04');
INSERT INTO LMENUS(LMENUID, LMENUNAME, LMENUURL, MENUID) VALUES('MENU11','SQL',' ','MENU04');

INSERT INTO LMENUS(LMENUID, LMENUNAME, LMENUURL, MENUID) VALUES('MENU12','자유게시판',' ','MENU05');
INSERT INTO LMENUS(LMENUID, LMENUNAME, LMENUURL, MENUID) VALUES('MENU13','최밥창문',' ','MENU05');

--commit;
