CREATE OR REPLACE
PACKAGE BODY PKG_MENUS AS

  PROCEDURE PROC_SEL_HMENUS
    (
        O_CUR   OUT     SYS_REFCURSOR
    ) AS
  BEGIN
    
    OPEN O_CUR FOR
    SELECT MENUID, MENUNAME
    FROM HMENUS
    ;
    
  END PROC_SEL_HMENUS;

  PROCEDURE PROC_SEL_LMENUS
    (
        IN_HMENUID  IN      VARCHAR2,
        O_CUR       OUT     SYS_REFCURSOR
    ) AS
  BEGIN
    
    OPEN O_CUR FOR
    SELECT LMENUID, LMENUNAME, LMENUURL, MENUID
    FROM LMENUS
    WHERE MENUID=IN_HMENUID
    ;
    
  END PROC_SEL_LMENUS;

END PKG_MENUS;