create or replace NONEDITIONABLE PACKAGE PKG_RESERVATION AS 

--INSERT
    PROCEDURE PROC_INS_RESERVATION
    (
        IN_PER_ID       IN  VARCHAR2
        ,IN_HOS_ID      IN  VARCHAR2
        ,IN_VAC_ID      IN  VARCHAR2
        ,IN_RES_DATE    IN  VARCHAR2
        ,O_ERRCODE      OUT VARCHAR2
        ,O_ERRMSG       OUT VARCHAR2
    );

--SELECT
    PROCEDURE PROC_SEL_RESERVATION
    (
        IN_RES_ID   IN  VARCHAR2
        ,IN_PER_ID   IN  VARCHAR2
        ,IN_HOS_ID   IN  VARCHAR2
        ,IN_VAC_ID   IN  VARCHAR2
        ,O_CUR      OUT  SYS_REFCURSOR
        ,O_ERRCODE      OUT VARCHAR2
        ,O_ERRMSG       OUT VARCHAR2
    );

--UPDATE
    PROCEDURE PROC_UP_RESERVATION
    (
        IN_RES_ID   IN VARCHAR2
        ,IN_PER_ID  IN VARCHAR2
        ,IN_HOS_ID  IN VARCHAR2
        ,IN_VAC_ID  IN VARCHAR2
        ,IN_RES_DATE    IN VARCHAR2
        ,O_ERRCODE      OUT VARCHAR2
        ,O_ERRMSG       OUT VARCHAR2
    );

--DELETE
    PROCEDURE PROC_DEL_RESERVATION
    (
        IN_RES_ID   IN VARCHAR2
        ,O_ERRCODE      OUT VARCHAR2
        ,O_ERRMSG       OUT VARCHAR2
    );


END PKG_RESERVATION;