SELECT * FROM PERSON_TBL;
SELECT * FROM COMMONS_TBL;
SELECT * FROM VACCINE_TBL;
SELECT * FROM HOSPITAL_TBL;
SELECT * FROM RESERVATION_TBL;
SELECT * FROM INJECTION_TBL;
SELECT * FROM VACCINE_IN_TBL;
SELECT * FROM ADMISSION_TBL;
SELECT * FROM DOCTOR_TBL;
SELECT * FROM TERAT_TBL;
SELECT * FROM DISCHARGE_TBL;
SELECT * FROM PATIENT_TBL;
SELECT * FROM ADMISSION_ROOMS_TBL;
SELECT * FROM ADMISSION_MEDICINES_TBL;

-----------------------------

--1. 병원별 총 환자수를 구하시오.(*환자는 진료를 받은 사람이라고 가정함) --최문준

SELECT A.HOS_ID, A.HOS_NAME, B.COM_VAL, A.PATIENT
        FROM
        (
            SELECT T3.HOS_ID, T3.HOS_NAME, T3.HOS_ADDR, COUNT(T1.PER_ID) AS PATIENT
            FROM TREAT_TBL T1, DOCTOR_TBL T2, HOSPITAL_TBL T3
            WHERE T1.DOC_ID = T2.DOC_ID
            AND T2.HOS_ID = T3.HOS_ID
            GROUP BY T3.HOS_ID, T3.HOS_NAME, T3.HOS_ADDR
        )A, COMMONS_TBL B
        WHERE A.HOS_ADDR = B.COM_ID
        ;

--2. 입원을 한번이라도 했던 사람들 중에서 몇번째 백신을 맞고 입원을 하였는지 구하시오. --정성균

SELECT T1.PER_ID, T2.INJ_DATE, T2.INJ_CNT, T3.VAC_ID
FROM ADMISSION_TBL T1, INJECTION_TBL T2, RESERVATION_TBL T3
WHERE T1.PER_ID = T3.PER_ID
AND T2.RES_ID = T3.RES_ID
GROUP BY T1.PER_ID, T2.INJ_DATE, T2.INJ_CNT, T3.VAC_ID
ORDER BY T1.PER_ID ASC;


--3. 사람 중에서 각 차수별 백신 접종률을 구하시오. (ex. 1차%, 2차%, 3차%) --최문준

SELECT A.INJ_CNT, ROUND((A.INJ_PERSON / COUNT(B.PER_ID)), 2) * 100 || '%' AS INJ_RATE
        FROM
        (
            SELECT T1.INJ_CNT, COUNT(T3.PER_ID) AS INJ_PERSON
            FROM INJECTION_TBL T1, PERSON_TBL T2, RESERVATION_TBL T3
            WHERE T1.RES_ID = T3.RES_ID
            AND T2.PER_ID = T3.PER_ID
            GROUP BY T1.INJ_CNT
        )A, PERSON_TBL B
        GROUP BY A.INJ_CNT, A.INJ_PERSON
        ORDER BY A.INJ_CNT ASC
        ;

--4. 백신 접종자 중 각 차수별 부작용으로 병원을 방문한 사람의 비율을 구하시오. --최문준

SELECT AA.INJ_CNT, ROUND((AA.PAT_PER / COUNT(BB.RES_ID)), 3) * 100 || '%' AS PCT
FROM
(
    SELECT B.INJ_CNT, COUNT(A.PAT_ID) AS PAT_PER
    FROM 
    (   
        SELECT T1.PAT_ID, T1.PER_ID, T1.HOS_ID
        FROM PATIENT_TBL T1, PERSON_TBL T2
        WHERE T1.PER_ID = T2.PER_ID
    ) A,
    (
        SELECT T2.INJ_CNT, T1.PER_ID, T1.HOS_ID
        FROM RESERVATION_TBL T1, INJECTION_TBL T2
        WHERE T1.RES_ID = T2.RES_ID
    ) B
    WHERE A.PER_ID = B.PER_ID
    AND A.HOS_ID = B.HOS_ID
    GROUP BY B.INJ_CNT
) AA, INJECTION_TBL BB
WHERE AA.INJ_CNT = BB.INJ_CNT
GROUP BY AA.INJ_CNT, AA.PAT_PER
ORDER BY AA.INJ_CNT
;

--5. 백신 접종자 연령대별 부작용이 일어날 확률을 구하시오. --김정희

--6. 병원 방문자들의 연령대별 평균 의료비를 구하시오. --정성균(진행 중)

SELECT CASE 1 <= T5.AGE WHEN
            
    , (T2.TREPER_TREPAY + T3.ADMPER_ROOMPAY + T4.ADMPER_MEDPAY) AS TLTPRICE
FROM PERSON_TBL T1,
(
    --진료받은사람별 진료비
    SELECT T2.PER_ID, SUM(T2.TRE_PAY) AS TREPER_TREPAY
    FROM PATIENT_TBL T1
        , TREAT_TBL T2
    WHERE T1.PAT_ID=T2.PAT_ID
    GROUP BY T2.PER_ID
) T2,
(
    --입원한사람별 병실비
    SELECT A.PER_ID, A.PER_NAME, SUM(B.ROOMPAY) AS ADMPER_ROOMPAY
    FROM
    (
        --사람 + 입원
        SELECT T1.PER_NAME, T1.PER_ID, T2.ADM_ID
        FROM PERSON_TBL T1, ADMISSION_TBL T2
        WHERE T1.PER_ID=T2.PER_ID
    ) A,
    (
        --입원건별 병실비
        SELECT T2.ADM_ID
            , SUM(TO_NUMBER(T1.EXP_VAL1)) AS ROOMPAY
        FROM COMMONS_TBL T1
            , ADMISSION_ROOMS_TBL T2
        WHERE T1.GRP_ID=T2.ADM_ROOM_GRP
            AND T1.COM_ID=T2.ADM_ROOM
        GROUP BY T2.ADM_ID
    ) B
    WHERE A.ADM_ID=B.ADM_ID
    GROUP BY A.PER_ID, A.PER_NAME
) T3,
(
    --입원한사람별 약값
    SELECT A.PER_ID, A.PER_NAME, SUM(B.MEDPAY) AS ADMPER_MEDPAY
    FROM
    (
        --사람 + 입원
        SELECT T1.PER_NAME, T1.PER_ID, T2.ADM_ID
        FROM PERSON_TBL T1, ADMISSION_TBL T2
        WHERE T1.PER_ID=T2.PER_ID
    ) A,
    (
        --입원건별 약값
        SELECT T2.ADM_ID
            , SUM(TO_NUMBER(T1.EXP_VAL1)*ADM_MED_QTY) AS MEDPAY
        FROM COMMONS_TBL T1
            , ADMISSION_MEDICINES_TBL T2
        WHERE T1.GRP_ID=T2.ADM_MED_GRP
            AND T1.COM_ID=T2.ADM_MED
        GROUP BY T2.ADM_ID
    ) B
    WHERE A.ADM_ID=B.ADM_ID
    GROUP BY A.PER_ID, A.PER_NAME
) T4,
(
    SELECT PER_ID, (TO_CHAR(SYSDATE, 'YYYY') - TO_NUMBER(DECODE(SUBSTR(PER_ID, 8, 1), 1, 19, 2, 19, 3, 20, 4, 20) || SUBSTR(PER_ID, 0, 2))) AS AGE
    FROM PERSON_TBL
) T5
WHERE T1.PER_ID = T2.PER_ID
    AND T1.PER_ID = T3.PER_ID
    AND T1.PER_ID = T4.PER_ID
    AND T1.PER_ID = T5.PER_ID
ORDER BY PER_NAME ASC
;

--7. 병원 방문자들이 사는 지역별 평균 의료비를 구하시오. --정성균


SELECT A.COM_VAL, TO_CHAR(AVG(B.TLTUSEROOM + C.TLTPRICE + TRE_PAY), '999,999,999') AS AVGPRICE
FROM
(
    SELECT T1.PER_ID, T3.COM_VAL
    FROM PATIENT_TBL T1, PERSON_TBL T2, COMMONS_TBL T3 --병원 방문자의 지역
    WHERE T1.PER_ID = T2.PER_ID
    AND T2.PER_ADDR_GRP = T3.GRP_ID
    AND T2.PER_ADDR = T3.COM_ID
) A,
(
    SELECT T1.ADM_ID, T1.PER_ID, SUM(T3.EXP_VAL1) AS TLTUSEROOM --병실사용료
    FROM ADMISSION_TBL T1, ADMISSION_ROOMS_TBL T2, COMMONS_TBL T3
    WHERE T1.ADM_ID = T2.ADM_ID
    AND T2.ADM_ROOM_GRP = T3.GRP_ID
    AND T2.ADM_ROOM = T3.COM_ID
    GROUP BY T1.ADM_ID, T1.PER_ID, T3.EXP_VAL1
) B, 
(
    SELECT T1.ADM_ID, SUM(T2.EXP_VAL1 * T1.ADM_MED_QTY) AS TLTPRICE --처방약품비
    FROM ADMISSION_MEDICINES_TBL T1, COMMONS_TBL T2
    WHERE T1.ADM_MED_GRP = T2.GRP_ID
    AND T1.ADM_MED = T2.COM_ID
    GROUP BY T1.ADM_ID
) C,
(
    SELECT T1.PER_ID, SUM(T2.TRE_PAY) AS TRE_PAY --진료비
    FROM PATIENT_TBL T1, TREAT_TBL T2
    WHERE T1.PAT_ID = T2.PAT_ID
    AND T1.PER_ID = T2.PER_ID
    GROUP BY T1.PER_ID
) D
WHERE A.PER_ID = B.PER_ID
AND B.ADM_ID = C.ADM_ID
AND B.PER_ID = D.PER_ID
GROUP BY A.COM_VAL
ORDER BY A.COM_VAL ASC;
 

--8. 각 병원별 병원 방문자들의 의료비 총 합계를 구하시오. --원재경

--9. 백신 접종자 중 병원을 한 번도 방문하지 않은 사람과 이들의 최종 접종 차수를 구하시오. --원재경

SELECT T2.PER_ID, T4.PER_NAME, COUNT(T2.PER_ID) AS 최종접종차수
FROM INJECTION_TBL T1, RESERVATION_TBL T2, PATIENT_TBL T3, PERSON_TBL T4
WHERE T1.RES_ID(+) =  T2.RES_ID
AND T1.INJ_DATE IS NOT NULL 
AND T2.PER_ID=T3.PER_ID(+)
AND T3.PER_ID IS NULL
AND T2.PER_ID=T4.PER_ID
GROUP BY T2.PER_ID, T4.PER_NAME;

--10. 사람 중에서 자기가 사는 지역에서 백신을 예약하고 접종한 사람을 구하시오. --정성균
SELECT A.PER_ID, A.PER_NAME, B.COM_VAL, A.HOS_ID, A.HOS_NAME
FROM
(
    SELECT T1.PER_ID, T1.PER_NAME, T1.PER_ADDR_GRP, T1.PER_ADDR, T4.HOS_ID, T4.HOS_NAME
    FROM PERSON_TBL T1, INJECTION_TBL T2, RESERVATION_TBL T3, HOSPITAL_TBL T4
    WHERE T1.PER_ID = T3.PER_ID
    AND T2.RES_ID = T3.RES_ID
    AND T3.HOS_ID = T4.HOS_ID
    AND T1.PER_ADDR_GRP = T4.HOS_ADDR_GRP
    AND T1.PER_ADDR = T4.HOS_ADDR
) A, COMMONS_TBL B
WHERE A.PER_ADDR_GRP = B.GRP_ID
AND A.PER_ADDR = B.COM_ID;


--11. 입원을 한 사람이 퇴원을 하기 위하여 지불하여야 하는 병원비를 구하시오. --유승화

--(단, 일일 병실 사용료는 다음과 같습니다.)
--(1인실 : 200,000원, 2인실 : 90,000원, 3인실 : 50,000원, 4인실 : 30,000원, 6인실 : 15,000원)
--(중환자실 : 70,000원)
/*

        ———————————————————————
        
        입원 ID | 사람 ID | 사람 이름 | 처방약품비 | 병실사용료 | 진료비 | 총 합계
        
        ———————————————————————



-----------------------------

*/
SELECT T1.ADM_ID
    , T1.PER_ID
    , T1.PER_NAME
    , TO_CHAR(T2.ROOMPAY,'999,999,999') AS ROOMPAY
    , TO_CHAR(T2.MEDPAY,'999,999,999') AS MEDPAY
    , TO_CHAR(T2.TRE_PAY,'999,999,999') AS TREPAY
    , TO_CHAR(T2.TOTALPAY,'999,999,999') AS TOTALPAY
FROM
(
    --사람 + 입원
    SELECT T1.PER_NAME, T1.PER_ID, T2.ADM_ID
    FROM PERSON_TBL T1, ADMISSION_TBL T2
    WHERE T1.PER_ID=T2.PER_ID
) T1,
(
    --입원건당 병실비 + 약값 + 진료비
    SELECT A.ADM_ID
        , A.ROOMPAY
        , B.MEDPAY
        , C.TRE_PAY
        , SUM(A.ROOMPAY+B.MEDPAY+C.TRE_PAY) AS TOTALPAY
    FROM
    (
        --입원건별 병실비
        SELECT T2.ADM_ID
            , SUM(TO_NUMBER(T1.EXP_VAL1)) AS ROOMPAY
        FROM COMMONS_TBL T1
            , ADMISSION_ROOMS_TBL T2
        WHERE T1.GRP_ID=T2.ADM_ROOM_GRP
            AND T1.COM_ID=T2.ADM_ROOM
        GROUP BY T2.ADM_ID
    ) A,
    (
        --입원건별 약값
        SELECT T2.ADM_ID
            , SUM(TO_NUMBER(T1.EXP_VAL1)*ADM_MED_QTY) AS MEDPAY
        FROM COMMONS_TBL T1
            , ADMISSION_MEDICINES_TBL T2
        WHERE T1.GRP_ID=T2.ADM_MED_GRP
            AND T1.COM_ID=T2.ADM_MED
        GROUP BY T2.ADM_ID
    ) B,
    (
        --입원건별 진료비
        SELECT T3.ADM_ID
            , T2.TRE_PAY
        FROM PATIENT_TBL T1
            , TREAT_TBL T2
            , ADMISSION_TBL T3
        WHERE T1.PAT_ID=T2.PAT_ID
            AND T2.TRE_ID=T3.TRE_ID
    ) C,
    ADMISSION_TBL T1
    WHERE T1.ADM_ID=A.ADM_ID
        AND T1.ADM_ID=B.ADM_ID
        AND T1.ADM_ID=C.ADM_ID
    GROUP BY A.ADM_ID, A.ROOMPAY, B.MEDPAY, C.TRE_PAY
) T2, DISCHARGE_TBL T3
WHERE T1.ADM_ID=T2.ADM_ID
    AND T1.ADM_ID=T3.ADM_ID
ORDER BY T1.ADM_ID ASC
;