/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-06-09 01:35:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Admin.programList;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import pkg.admin.DTO.MenuDTO;
import pkg.admin.DTO.ProgramDTO;
import java.util.List;

public final class programList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("pkg.admin.DTO.MenuDTO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("pkg.admin.DTO.ProgramDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("  integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("		body{\r\n");
      out.write("			margin:0px;\r\n");
      out.write("			font-size:12px;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		#wrap{\r\n");
      out.write("		\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("		.search{\r\n");
      out.write("			width:700px;\r\n");
      out.write("			border:0px solid red;\r\n");
      out.write("			padding:4px 0px 4px 0px;\r\n");
      out.write("			\r\n");
      out.write("			clear:both;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.row{\r\n");
      out.write("			width:900px;\r\n");
      out.write("			border:0px solid red;\r\n");
      out.write("			/*padding:4px 0px 4px 0px;*/\r\n");
      out.write("			\r\n");
      out.write("			clear:both;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.col1{\r\n");
      out.write("			border:1px solid #444;width:50px;padding:3px 0px 3px 0px;display:block;\r\n");
      out.write("			text-align:center;float:left;\r\n");
      out.write("		}\r\n");
      out.write("		.col2{\r\n");
      out.write("			border:1px solid #444;width:150px;padding:4px 0px 5px 0px;display:block;\r\n");
      out.write("			text-align:center;float:left;\r\n");
      out.write("		}\r\n");
      out.write("		.col3{\r\n");
      out.write("			border:1px solid #444;width:150px;padding:4px 0px 5px 0px;display:block;\r\n");
      out.write("			text-align:center;float:left;\r\n");
      out.write("		}\r\n");
      out.write("		.col4{\r\n");
      out.write("			border:1px solid #444;width:230px;padding:4px 0px 5px 0px;display:block;\r\n");
      out.write("			text-align:center;float:left;\r\n");
      out.write("		}\r\n");
      out.write("		.col5{\r\n");
      out.write("			border:1px solid #444;width:150px;padding:4px 0px 5px 0px;display:block;\r\n");
      out.write("			text-align:center;float:left;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/jscss/js/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		$(\"#btnSave\").click(function(){\r\n");
      out.write("			var sendData = {};\r\n");
      out.write("			var datas = [];//sendData는 배열로 이루어진 객체, datas는 객체들의 배열, objRow는 데이터 하나를 가리키는 객체\r\n");
      out.write("			var objRow = {};\r\n");
      out.write("			var pid = \"\";\r\n");
      out.write("			var menuid = \"\";\r\n");
      out.write("			var fileName = \"\";\r\n");
      out.write("			var fileUrl = \"\";\r\n");
      out.write("			for(var i=0;i<$(\"input[name='pid']\").length;i++){\r\n");
      out.write("				objRow.pId=$(\"input[name='pid']\").eq(i).val();\r\n");
      out.write("				objRow.pName=$(\"input[name='pName']\").eq(i).val();\r\n");
      out.write("				objRow.menuID=$(\"select[name='menuID']\").eq(i).val();\r\n");
      out.write("				objRow.fileName=$(\"input[name='fileName']\").eq(i).val();\r\n");
      out.write("				objRow.fileUrl=$(\"input[name='fileUrl']\").eq(i).val();\r\n");
      out.write("				datas.push(objRow);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$(\"select[name='menuID']\").change(function(){\r\n");
      out.write("			var selIdx = $(this).attr(\"idx\");\r\n");
      out.write("			$(\"input[name='hiddenVal']\").eq(selIdx).val(\"u\");\r\n");
      out.write("		});\r\n");
      out.write("		$(\"input[name='fileName']\").change(\r\n");
      out.write("				function(){\r\n");
      out.write("					var selectedIdx = $(this).attr(\"idx\");\r\n");
      out.write("					\r\n");
      out.write("					$(\"input[name='hiddenVal']\").eq(selectedIdx).val(\"U\");\r\n");
      out.write("				}\r\n");
      out.write("		);\r\n");
      out.write("		\r\n");
      out.write("		$(\"input[name='fileUrl']\").change(\r\n");
      out.write("				function(){\r\n");
      out.write("					var selectedIdx = $(this).attr(\"idx\");\r\n");
      out.write("					\r\n");
      out.write("					$(\"input[name='hiddenVal']\").eq(selectedIdx).val(\"U\");\r\n");
      out.write("				}\r\n");
      out.write("		);\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$(\"#btnAdd\").click(function(){\r\n");
      out.write("			getMenuList();\r\n");
      out.write("			//ajax로 실시간 변동되는 데이터를 가져와야 한다(목록 내용이 언제 바뀔지 모르므로)\r\n");
      out.write("			var strHTML = \"\";\r\n");
      out.write("			strHTML += '<div class=\"row\">';\r\n");
      out.write("			strHTML += '<span class=\"col1\"><input type=\"checkbox\" name=\"chk\" /></span>';\r\n");
      out.write("			strHTML += '<span class=\"col2\"><input type=\"text\" name=\"pid\"  class=\"col2\"/></span>';\r\n");
      out.write("			strHTML += '<span class=\"col4\"></span>';\r\n");
      out.write("			strHTML += '<span class=\"col2\">';\r\n");
      out.write("			strHTML += '<select name=\"menuID\">';\r\n");
      out.write("			strHTML += '<option value=\"\">---선택하세요---</option>';\r\n");
      out.write("			strHTML += '</select>';\r\n");
      out.write("			strHTML += '</span>';\r\n");
      out.write("			strHTML += '<span class=\"col2\"><input type=\"text\" name=\"fileName\" class=\"col2\"/></span>';\r\n");
      out.write("			strHTML += '<span class=\"col2\"><input type=\"text\" name=\"fileUrl\"  class=\"col2\"/></span>';\r\n");
      out.write("			strHTML += '<span><input type=\"text\" name=\"hidVal\" value=\"I\"/></span>';\r\n");
      out.write("			strHTML += '</div>';\r\n");
      out.write("			\r\n");
      out.write("			$(\"#rows\").append(strHTML);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	var getMenuList = function(){\r\n");
      out.write("		//ajax 자체를 불러올 함수 쪽에서 작성하는게 좋음\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : \"menuList\",\r\n");
      out.write("			//data : this.data,\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			async : false,//true 하면 row에 추가되기 전에 데이터를 받아버리기 때문\r\n");
      out.write("			dataType : \"json\",\r\n");
      out.write("			success : function(data){\r\n");
      out.write("				//ajax에서 왠만하면 리턴 안쓰는게 좋음\r\n");
      out.write("				//여기에서 불러와서 만들 strHTML을 만드는게 안전하다\r\n");
      out.write("				var strHTML = \"\";\r\n");
      out.write("				strHTML += '<div class=\"row\">';\r\n");
      out.write("				strHTML += '<span class=\"col1\"><input type=\"checkbox\" name=\"chk\" /></span>';\r\n");
      out.write("				strHTML += '<span class=\"col2\"><input type=\"text\" name=\"pid\"  class=\"col2\"/></span>';\r\n");
      out.write("				strHTML += '<span class=\"col4\"><input type=\"text\" name=\"pName\" class=\"col4\"/></span>';\r\n");
      out.write("				strHTML += '<span class=\"col2\">';\r\n");
      out.write("				strHTML += '<select name=\"menuID\">';\r\n");
      out.write("				strHTML += '<option value=\"\">---선택하세요---</option>';\r\n");
      out.write("				$(data).each(function(){\r\n");
      out.write("					strHTML += '<option value=\"'+this.menuID+'\">';\r\n");
      out.write("					strHTML += this.menuName+'</option>';\r\n");
      out.write("				});\r\n");
      out.write("				strHTML += '</select>';\r\n");
      out.write("				strHTML += '</span>';\r\n");
      out.write("				strHTML += '<span class=\"col2\"><input type=\"text\" name=\"fileName\" class=\"col2\"/></span>';\r\n");
      out.write("				strHTML += '<span class=\"col2\"><input type=\"text\" name=\"fileUrl\"  class=\"col2\"/></span>';\r\n");
      out.write("				strHTML += '<span><input type=\"text\" name=\"hiddenVal\" value=\"i\"/></span>';\r\n");
      out.write("				strHTML += '</div>';\r\n");
      out.write("			},\r\n");
      out.write("			fail:function(){\r\n");
      out.write("				alert(\"쉴패.\");\r\n");
      out.write("			},\r\n");
      out.write("			complete : function(){\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	List<ProgramDTO> programList = (List<ProgramDTO>)request.getAttribute("programList");
	List<MenuDTO> menuList = (List<MenuDTO>)request.getAttribute("menuList");

      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("	<input type=\"text\" name=\"search\" id=\"search\" value=\"\"/>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("	<input type=\"button\" value=\"조회\" id=\"btnSearch\"/>\r\n");
      out.write("	<input type=\"button\" value=\"추가\" id=\"btnAdd\"/>\r\n");
      out.write("	<input type=\"button\" value=\"저장\" id=\"btnSave\"/>\r\n");
      out.write("	<input type=\"button\" value=\"삭제\" id=\"btnDelete\"/>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("	<span class=\"col1\">\r\n");
      out.write("		<input type=\"checkbox\" name=\"chkT\" id=\"chkT\" />\r\n");
      out.write("	</span>\r\n");
      out.write("	<span class=\"col2\">아이디</span>\r\n");
      out.write("	<span class=\"col4\">프로그램명</span>\r\n");
      out.write("	<span class=\"col2\">연결메뉴</span>\r\n");
      out.write("	<span class=\"col2\">JSP</span>\r\n");
      out.write("	<span class=\"col2\">URL</span>\r\n");
      out.write("	<span></span>\r\n");
      out.write("</div>\r\n");
      out.write("	");
 int i = 0; 
      out.write('\r');
      out.write('\n');
      out.write('	');
 for(ProgramDTO pdto : programList){ 
      out.write("\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<span class=\"col1\">\r\n");
      out.write("				<input type=\"checkbox\" name=\"chk\"/>\r\n");
      out.write("			</span>\r\n");
      out.write("			<span class=\"col2\">\r\n");
      out.write("				<input type=\"text\" name=\"pid\" value=\"");
      out.print(pdto.getpID() );
      out.write("\" readonly/>\r\n");
      out.write("			</span>\r\n");
      out.write("			<span class=\"col4\"><input type=\"text\" name=\"pName\" value=\"");
      out.print(pdto.getpName() );
      out.write("\" readonly/></span>\r\n");
      out.write("			<span class=\"col2\">\r\n");
      out.write("				<select name=\"menuID\" idx=\"");
      out.print(i );
      out.write("\">\r\n");
      out.write("					<option value=\"\">---선택---</option>\r\n");
      out.write("				");
 for(MenuDTO mdto : menuList){ 
      out.write("\r\n");
      out.write("					<option value=\"");
      out.print(mdto.getMenuID() );
      out.write('"');
      out.write('>');
      out.print(mdto.getMenuName() );
      out.write("</option>\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("				</select>\r\n");
      out.write("			</span>\r\n");
      out.write("			<span class=\"col2\">");
      out.print(pdto.getpFileName() );
      out.write("</span>\r\n");
      out.write("			<span class=\"col2\">");
      out.print(pdto.getFileUrl() );
      out.write("</span>\r\n");
      out.write("			<span><input type=\"hidden\" name=\"hiddenVal\"/></span>\r\n");
      out.write("		</div>\r\n");
      out.write("	");
 i++; 
      out.write('\r');
      out.write('\n');
      out.write('	');
} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
