create or replace NONEDITIONABLE PACKAGE BODY PKG_BOARDS AS

  PROCEDURE PROC_SEL_BOARD
    (
        IN_IDX     IN  VARCHAR2
        ,O_CUR  OUT SYS_REFCURSOR
    ) AS
  BEGIN
    
    OPEN O_CUR FOR
    SELECT IDX, TITLE, USERID, REGNUM, CONTENT,
        DECODE(
            TO_CHAR(REGDATE, 'YYYYMMDD'),--A
            TO_CHAR(SYSDATE, 'YYYYMMDD'),--B
            TO_CHAR(REGDATE, 'HH24:MI:SS'),--A=B이면 이 값 표시
            TO_CHAR(REGDATE, 'YYYY-MM-DD')--아니면 이 값 표시
        ) AS REGDATES
    FROM BOARDS
    WHERE TO_CHAR(IDX) LIKE '%'||IN_IDX||'%'
    ORDER BY TO_CHAR(REGDATE, 'YYYYMMDD') DESC,
            TO_CHAR(REGDATE, 'HH24:MI:SS') DESC
    ;
  END PROC_SEL_BOARD;
  
  

  PROCEDURE PROC_SEL_BOARD_CONTENT
    (
        IN_IDX     IN  VARCHAR2
        ,O_CUR  OUT SYS_REFCURSOR
    ) AS
  BEGIN
    OPEN O_CUR FOR
    SELECT IDX, USERID, TITLE,
        TO_CHAR(REGDATE, 'YYYY/MM/DD HH24:MI:SS') AS REGDATE,
        CONTENT
    FROM BOARDS
    WHERE IDX=IN_IDX
    ;
  END PROC_SEL_BOARD_CONTENT;




  PROCEDURE PROC_UP_BOARD
    (
        IN_IDX      IN  VARCHAR2
        ,IN_USERID  IN  VARCHAR2
        ,IN_TITLE   IN  VARCHAR2
        ,IN_CONTENT IN  VARCHAR2
    ) AS
  BEGIN
    UPDATE BOARDS
    SET USERID=IN_USERID,
        TITLE=IN_TITLE,
        CONTENT=IN_CONTENT
    WHERE IDX=IN_IDX
    ;
  END PROC_UP_BOARD;



  PROCEDURE PROC_DEL_BOARD
    (
        IN_IDX  IN  VARCHAR2
    ) AS
  BEGIN
    DELETE FROM BOARDS
    WHERE IDX=IN_IDX
    ;
  END PROC_DEL_BOARD;
  
  
  

  PROCEDURE PROC_SAVE_BOARD
  (
        IN_IDX      IN  VARCHAR2
        ,IN_USERID  IN  VARCHAR2
        ,IN_TITLE   IN  VARCHAR2
        ,IN_CONTENT IN  VARCHAR2
        ,IN_REGDATE IN  VARCHAR2
  ) AS
        V_NEW_IDX      INT;
  BEGIN
    
    SELECT TO_NUMBER(NVL(MAX(IDX),1))+1
    INTO V_NEW_IDX
    FROM BOARDS;
    
    MERGE INTO BOARDS
    USING DUAL
    ON(IDX=IN_IDX)
    WHEN MATCHED THEN
        UPDATE
        SET TITLE=IN_TITLE,
            USERID=IN_USERID
    WHEN NOT MATCHED THEN
        INSERT(IDX, TITLE, CONTENT, USERID, REGNUM, REGDATE)
        VALUES(V_NEW_IDX, IN_TITLE, IN_CONTENT, IN_USERID, V_NEW_IDX, IN_REGDATE)
    ;
    
  END PROC_SAVE_BOARD;

END PKG_BOARDS;