/*
DROP TABLE ADMISSION_MEDICINES_TBL;
DROP TABLE ADMISSION_ROOMS_TBL;
DROP TABLE ADMISSION_TBL;
DROP TABLE COMMONS_TBL;
DROP TABLE DISCHARGE_TBL;
DROP TABLE DOCTOR_TBL;
DROP TABLE HOSPITAL_TBL;
DROP TABLE INJECTION_TBL;
DROP TABLE PATIENT_TBL;
DROP TABLE PERSON_TBL;
DROP TABLE RESERVATION_TBL;
DROP TABLE TREAT_TBL;
DROP TABLE VACCINE_IN_TBL;
DROP TABLE VACCINE_TBL;
*/