/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-06-03 02:16:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Admin.authList;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import pkg.admin.DTO.AuthDTO;
import java.util.List;

public final class authList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("pkg.admin.DTO.AuthDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>AuthList</title>\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("  integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/jscss/js/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/jscss/js/authList/authList.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $(\"#btnSearch\").on(\"click\",function(){\r\n");
      out.write("        location.href=\"authList?authNameSearch=\"+$(\"#authNameSearch\").val();\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(\"#btnAdd\").click(function(){\r\n");
      out.write("    	var strHTML = \"\";\r\n");
      out.write("    	strHTML += '<tr style=\"background-color:#BBB\">';\r\n");
      out.write("    	strHTML += '<td width=\"100px\" height=\"30px\" align=\"center\">';\r\n");
      out.write("    		strHTML += '<input type=\"checkbox\" name=\"chk\" value=\"0\"/>';\r\n");
      out.write("    	strHTML += '</td>';\r\n");
      out.write("    	strHTML += '<td width=\"200px\" height=\"30px\" align=\"center\"><input type=\"text\" name=\"authID\" id=\"\" value=\"\" readonly/></td>';\r\n");
      out.write("    	strHTML += '<td width=\"400px\" height=\"30px\" align=\"center\"><input type=\"text\" name=\"authName\" id=\"\" value=\"\"/></td>';\r\n");
      out.write("    	strHTML += '<td width=\"30px\" height=\"30px\" align=\"center\">';\r\n");
      out.write("    		strHTML += '<input type=\"text\" style=\"width:10px\" name=\"gbn\" value=\"i\"/>';\r\n");
      out.write("    	strHTML += '</td>';\r\n");
      out.write("		strHTML += '</tr>';\r\n");
      out.write("		\r\n");
      out.write("		$(\"#authTbl\").append(strHTML);\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(\"input[name='authName']\").change(function(){\r\n");
      out.write("    	var chgIdx = $(\"input[name='authName']\").index(this);\r\n");
      out.write("    	//alert(chgIdx);\r\n");
      out.write("		$(\"input[name='gbn']\").eq(chgIdx).val(\"u\");\r\n");
      out.write("		//boardContent 밑의 idx번째 boardRow\r\n");
      out.write("		$(\"#authTbl tr\").eq(chgIdx+2).children().css(\"background-color\",\"#BBB\");\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(\"#btnSave\").click(function(){\r\n");
      out.write("    	//빈 값 처리\r\n");
      out.write("    	var isOK = true;\r\n");
      out.write("    	$(\"input[name='authName']\").each(function(){\r\n");
      out.write("    		if($(this).val==\"\" || $(this).val==null){\r\n");
      out.write("    			isOK = false;\r\n");
      out.write("    		}\r\n");
      out.write("    	});\r\n");
      out.write("    	if(!isOK){\r\n");
      out.write("    		alert(\"입력되지 않은 값이 있습니다\");\r\n");
      out.write("    		return;\r\n");
      out.write("    	}\r\n");
      out.write("    	$(\"#authListForm\").attr(\"action\",\"saveAuthList\");\r\n");
      out.write("    	$(\"#authListForm\").submit();\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(\"#chkT\").on(\"click\",function(){\r\n");
      out.write("    	$(\"input[name='chk']\").each(function(){\r\n");
      out.write("    		if($(\"#chkT\").prop(\"checked\")){\r\n");
      out.write("    			$(this).prop(\"checked\",true);\r\n");
      out.write("        	}else{\r\n");
      out.write("        		$(this).prop(\"checked\",false);\r\n");
      out.write("        	}\r\n");
      out.write("    	});\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    $(\"#btnDelete\").click(function(){\r\n");
      out.write("    	var delHTML = '';\r\n");
      out.write("    	\r\n");
      out.write("    	delHTML += '<form name=\"delForm\" id=\"delForm\" method=\"post\">';\r\n");
      out.write("		$(\"input[name='chk']\").each(function(){\r\n");
      out.write("			if($(this).is(\":checked\")){\r\n");
      out.write("				delHTML += '<input type=\"hidden\" name=\"authID\" value=\"'+\"delIdx ->authID\"+'\"/>';\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		delHTML += '</form>';\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$(\"#delFormDiv\").html(delHTML);\r\n");
      out.write("		$(\"#delForm\").attr(\"action\",\"deleteBoard\");\r\n");
      out.write("		$(\"#delForm\").submit();\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	List<AuthDTO> list = (List<AuthDTO>)request.getAttribute("authList");
	String authNameSearch = (request.getAttribute("authNameSearch")==null)? "" : (String)request.getAttribute("authNameSearch");


      out.write("\r\n");
      out.write("<form name=\"authListForm\" id=\"authListForm\" method=\"post\">\r\n");
      out.write("<table cellpadding=\"0\" cellspacing=\"0\" width=\"700px\" align=\"center\" border=\"1px\" id=\"authTbl\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"700px\" height=\"30px\" align=\"center\" colspan=\"3\">\r\n");
      out.write("			<input type=\"text\" name=\"authNameSearch\" id=\"authNameSearch\" value=\"");
      out.print(authNameSearch );
      out.write("\"/>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("			<input type=\"button\" value=\"조회\" id=\"btnSearch\"/>\r\n");
      out.write("			<input type=\"button\" value=\"추가\" id=\"btnAdd\"/>\r\n");
      out.write("			<input type=\"button\" value=\"저장\" id=\"btnSave\"/>\r\n");
      out.write("			<input type=\"button\" value=\"삭제\" id=\"btnDelete\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"100px\" height=\"30px\" align=\"center\">\r\n");
      out.write("			<input type=\"checkbox\" name=\"chkT\" id=\"chkT\" value=\"\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td width=\"200px\" height=\"30px\" align=\"center\" name=\"authIdT\">권한ID</td>\r\n");
      out.write("		<td width=\"400px\" height=\"30px\" align=\"center\" name=\"authNameT\">권한이름</td>\r\n");
      out.write("		<td width=\"30px\" height=\"30px\" align=\"center\">\r\n");
      out.write("			<input type=\"text\" style=\"width:10px\" name=\"gbnT\" value=\"\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("		");
 int index=1;
		for(AuthDTO dto : list){
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("			<td width=\"100px\" height=\"30px\" align=\"center\">\r\n");
      out.write("				<input type=\"checkbox\" name=\"chk\" value=\"");
      out.print(index );
      out.write("\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td width=\"200px\" height=\"30px\" align=\"center\" name=\"authID\">\r\n");
      out.write("				<input type=\"text\" name=\"authID\" id=\"\" value=\"");
      out.print(dto.getAuthID() );
      out.write("\" readonly/>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td width=\"400px\" height=\"30px\" align=\"center\">\r\n");
      out.write("				<input type=\"text\" name=\"authName\" id=\"\" value=\"");
      out.print(dto.getAuthName() );
      out.write("\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td width=\"30px\" height=\"30px\" align=\"center\">\r\n");
      out.write("				<input type=\"text\" style=\"width:10px\" name=\"gbn\" value=\"\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");
 index++;
		}
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("<div id=\"delFormDiv\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
