--19. 60점미만이면 재시험이라고 하면 재시험을 쳐야 하는 시험과 학생수를 보여주세요

SELECT T3.PID, T3.SUBID, T3.ENAME, COUNT(*) 
FROM SCORES T1, STUDENTS T2, EXAMS T3
WHERE T1.SID = T2.SID
AND T1.PID = T3.PID AND T1.SUBID = T3.SUBID
AND T1.SCORE < 60
GROUP BY T3.PID, T3.SUBID, T3.ENAME
;

SELECT * FROM SCORES T1, STUDENTS T2, EXAMS T3
WHERE T1.SID = T2.SID
AND T1.PID = T3.PID AND T1.SUBID = T3.SUBID
AND T1.SCORE < 60