--13. 각 과목(시험아님)별로 평균점수를 구해주세요
SELECT * FROM SUBJECTS;
SELECT * FROM SCORES;

SELECT SUBID, AVG(SCORE), SUM(SCORE) FROM SCORES
GROUP BY SUBID
;

SELECT A.SUBID, A.SUBNAME, AVG(NVL(B.SCORE, 0)) FROM
(
    SELECT T1.SID, T1.SNAME, T2.SUBID, T2.SNAME AS SUBNAME FROM STUDENTS T1, SUBJECTS T2
) A, SCORES B
WHERE A.SID = B.SID(+) AND A.SUBID = B.SUBID(+)
GROUP BY A.SUBID, A.SUBNAME
ORDER BY A.SUBID
;