create or replace NONEDITIONABLE PACKAGE PKG_DRIVER AS 
        
--1. INSERT DRIVER
    PROCEDURE PRO_INS_DRIVERS
    (
        IN_DR_NAME  IN  VARCHAR2
        ,IN_DR_TEL  IN  VARCHAR2
        ,IN_DR_GENDER  IN  VARCHAR2
        --
        ,O_ERRCODE   OUT VARCHAR2
        ,O_ERRMSG   OUT VARCHAR2
    );

--2. UPDATE MEMBER
    PROCEDURE PROC_UP_DR_MEMBER
    (
        IN_DR_ID    IN  VARCHAR2
        ,IN_DR_NAME IN  VARCHAR2
        ,IN_DR_TEL  IN  VARCHAR2
        ,IN_DR_GENDER   IN  VARCHAR2
        --
        ,O_ERRCODE   OUT VARCHAR2
        ,O_ERRMSG   OUT VARCHAR2
    );

--3. MERGE MEMBER
    PROCEDURE PROC_MER_DR_MEMBER
    (
        IN_DR_ID    IN  VARCHAR2
        ,IN_DR_NAME IN  VARCHAR2
        ,IN_DR_TEL  IN  VARCHAR2
        ,IN_DR_GENDER   IN  VARCHAR2
        --
        ,O_ERRCODE   OUT VARCHAR2
        ,O_ERRMSG   OUT VARCHAR2
    );
    
--4. SELECT DRIVER
    PROCEDURE PROC_SEL_DRIVER
    (
        IN_DR_ID    IN  VARCHAR2
        ,IN_DR_NAME IN  VARCHAR2
        ,O_CUR  OUT SYS_REFCURSOR
    );
    
--5. 
    PROCEDURE PROC_UP_POINT
    (
        IN_R_TEL    IN  VARCHAR2
    );
    
--6. 수익
    PROCEDURE PROC_PROFIT
    (
        O_CUR   OUT SYS_REFCURSOR
    );
END PKG_DRIVER;