create or replace NONEDITIONABLE PACKAGE PKG_INJECTION AS 

--INSERT
    PROCEDURE PROC_INS_INJECTION
    (
        IN_RES_ID   IN VARCHAR2
        ,IN_INJ_DATE     IN VARCHAR2
        ,O_ERRCODE      OUT VARCHAR2
        ,O_ERRMSG       OUT VARCHAR2
    );

--SELECT
    PROCEDURE PROC_SEL_INJECTION
    (
        IN_RES_ID   IN VARCHAR2
        ,O_CUR   OUT SYS_REFCURSOR
        ,O_ERRCODE      OUT VARCHAR2
        ,O_ERRMSG       OUT VARCHAR2
    );

--UPDATE
    PROCEDURE PROC_UP_INJECTION
    (
        IN_RES_ID   IN VARCHAR2
        ,IN_INJ_DATE    IN VARCHAR2
        ,IN_INJ_CNT     IN VARCHAR2
        ,O_ERRCODE      OUT VARCHAR2
        ,O_ERRMSG       OUT VARCHAR2
    );

--DELETE
    PROCEDURE PROC_DEL_INJECTION
    (
        IN_RES_ID   IN VARCHAR2
        ,O_ERRCODE      OUT VARCHAR2
        ,O_ERRMSG       OUT VARCHAR2
    );

END PKG_INJECTION;