/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-02 06:59:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Boards;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"..\\css\\board.css\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>TestBoard</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("<form action=\"./boardList_ok.jsp\" method=\"post\" name=\"boardForm\" id=\"boardForm\">\r\n");
      out.write("	<div id=\"btns\">\r\n");
      out.write("		<div class=\"btn_space\"></div>\r\n");
      out.write("		<div class=\"btn_contents\">\r\n");
      out.write("			<span class=\"btn\">조회</span>\r\n");
      out.write("			<span class=\"btn\">추가</span>\r\n");
      out.write("			<span class=\"btn\">삭제</span>\r\n");
      out.write("			<span class=\"btn\">저장</span>\r\n");
      out.write("		</div><!-- btn_contents -->\r\n");
      out.write("	</div><!-- btns -->\r\n");
      out.write("	<div id=\"boards\">\r\n");
      out.write("		<div class=\"row_head\">\r\n");
      out.write("			<span class=\"col_chk\">\r\n");
      out.write("				<input type=\"checkbox\" name=\"chkAll\" id=\"chkAll\"/>\r\n");
      out.write("			</span>\r\n");
      out.write("			<span class=\"col_idx\">번호</span>\r\n");
      out.write("			<span class=\"col_title\">제목</span>\r\n");
      out.write("			<span class=\"col_userID\">작성자</span>\r\n");
      out.write("			<span class=\"col_regdate\">작성일</span>\r\n");
      out.write("			<span type=\"hidden\"></span>\r\n");
      out.write("		</div><!-- row_head -->\r\n");
      out.write("		<div class=\"row_body\">\r\n");
      out.write("			<span class=\"col_chk\">\r\n");
      out.write("				<input type=\"checkbox\" name=\"chks\" id=\"chk0\"/>\r\n");
      out.write("			</span>\r\n");
      out.write("			<span class=\"col_idx\" name=\"idx\">1</span>\r\n");
      out.write("			<span class=\"col_title\" name=\"titles\" value=\"제목1\">\r\n");
      out.write("				\r\n");
      out.write("			</span>\r\n");
      out.write("			<span class=\"col_userID\" name=\"users\" value=\"작성자1\">\r\n");
      out.write("				\r\n");
      out.write("			</span>\r\n");
      out.write("			<span class=\"col_regdate\">123</span>\r\n");
      out.write("			<input type=\"hidden\" name=\"gbns\" value=\"\"/><!-- new/up/del -->\r\n");
      out.write("		</div><!-- row_body -->\r\n");
      out.write("	</div><!-- boards -->\r\n");
      out.write("</form><!-- boardForm -->\r\n");
      out.write("</div><!-- wrap -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
