/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-18 06:00:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>index</title>\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("  integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		$(\"#btnList\").click(function(){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				dataType : \"xml\",\r\n");
      out.write("				url : \"stock.do?jspURL=ajaxXML\",\r\n");
      out.write("				success : function(XML){\r\n");
      out.write("					var strHTML = \"<div>\";\r\n");
      out.write("					var sID= \"\";var sName= \"\";var sInfo = \"\";\r\n");
      out.write("					var XMLs = XML.getElementsByTagName(\"stock\");\r\n");
      out.write("					for(var i=0;i<XMLs.length;i++){\r\n");
      out.write("						sID = XMLs[i].childNodes[0].childNodes[0].nodeValue;\r\n");
      out.write("						sName = XMLs[i].childNodes[1].childNodes[0].nodeValue;\r\n");
      out.write("						sInfo = XMLs[i].childNodes[2].childNodes[0].nodeValue;\r\n");
      out.write("						\r\n");
      out.write("						strHTML += \"<div> ID : \"+sID+\"</div>\";\r\n");
      out.write("						strHTML += \"<div> 종목명 : \"+sName+\"</div>\";\r\n");
      out.write("						strHTML += \"<div> 회사정보 : \"+sInfo+\"</div>\";\r\n");
      out.write("					}\r\n");
      out.write("					strHTML += \"</div>\";\r\n");
      out.write("					\r\n");
      out.write("					$(\"#msgXML\").html(strHTML);\r\n");
      out.write("					\r\n");
      out.write("				},\r\n");
      out.write("				fail : function(){\r\n");
      out.write("					alert(\"쉴패~~~!!~!\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});//$(\"#btnList\").click()\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$(\"#btnList2\").click(function(){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				dataType : \"json\",\r\n");
      out.write("				data : {\r\n");
      out.write("					jspURL : \"ajaxJSON\",\r\n");
      out.write("					userID : \"userID\"\r\n");
      out.write("				},\r\n");
      out.write("				type : \"get\",\r\n");
      out.write("				url : \"stock.do\",\r\n");
      out.write("				async : true,\r\n");
      out.write("				success : function(obj){\r\n");
      out.write("					var strHTML = \"<div>\";\r\n");
      out.write("					$(obj).each(function(){\r\n");
      out.write("						strHTML += \"<div>ID : \"+this.sid+\"</div>\";\r\n");
      out.write("						strHTML += \"<div>이름 : \"+this.sname+\"</div>\";\r\n");
      out.write("						strHTML += \"<div>회사설명 : \"+this.sinfo+\"</div>\";\r\n");
      out.write("					});\r\n");
      out.write("					strHTML += \"</div>\";\r\n");
      out.write("					\r\n");
      out.write("					$(\"#msgJSON\").html(strHTML);\r\n");
      out.write("					\r\n");
      out.write("				},\r\n");
      out.write("				fail : function(){\r\n");
      out.write("					alert(\"쉴패~~~!!~!\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});//$(\"#btnList2\").click()\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<a href=\"stock.do?jspURL=list\">주식목록</a>\r\n");
      out.write("	<a href=\"stock.do?jspURL=write\">주식추가</a>\r\n");
      out.write("	<a href=\"stock.do?jspURL=ajaxXML\">XML</a>\r\n");
      out.write("	<a href=\"stock.do?jspURL=ajaxJSON\">JSON</a>\r\n");
      out.write("<div>\r\n");
      out.write("	<input type=\"button\" value=\"XML\" id=\"btnList\"/>\r\n");
      out.write("	<div id=\"msgXML\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("	<input type=\"button\" value=\"JSON\" id=\"btnList2\"/>\r\n");
      out.write("	<div id=\"msgJSON\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
