--집계함수,  MAX() - 최대값, MIN() - 최소값

SELECT COUNT(*) FROM SCORES;

SELECT MAX(SCORE) FROM SCORES;
SELECT MIN(SCORE) FROM SCORES;

SELECT * FROM SCORES;

--1. 도대체 왜 MAX, MIN 집계함수라고 하는거지??
SELECT SID, SUM(SCORE), AVG(SCORE), MAX(SCORE), MIN(SCORE)
FROM SCORES
WHERE SID = 'S001' OR SID = 'S002'
GROUP BY SID
ORDER BY SID ASC
;
SELECT * FROM SCORES WHERE SID = 'S001' OR SID = 'S002'
;

--2. 학생별로 최고점과 최저점을 찾아라
SELECT SID, MAX(SCORE) AS HIGHSCORE, MIN(SCORE) AS LOWSCORE
FROM SCORES
GROUP BY SID
ORDER BY SID ASC
;

--3. 정렬방식으로서 MAX ,MIN
SELECT MAX(BIRTH), MIN(BIRTH) FROM PROFESSORS;

SELECT * FROM PROFESSORS
ORDER BY BIRTH DESC
;

SELECT * FROM PROFESSORS
ORDER BY BIRTH ASC
;

--MAX, MIN 집계함수에서 사용하는데 문자열에 사용할때
--SID, 총점, 평균, 최고점, 최저점
SELECT SID, SUM(SCORE), AVG(SCORE), MAX(SCORE), MIN(SCORE)
FROM SCORES
WHERE SID = 'S001' OR SID = 'S002'
GROUP BY SID
ORDER BY SID ASC
;
SELECT *
FROM SCORES
WHERE SID = 'S001' OR SID = 'S002'

ORDER BY SID ASC
;

