--14. 모든학생들의 총점과 평균 점수를 보여주세요

SELECT * FROM STUDENTS;
SELECT * FROM SUBJECTS;
SELECT * FROM EXAMS;
SELECT * FROM SCORES;

-- INLINE VIEW
SELECT A.SID, A.SNAME, SUM(B.SCORE), ROUND(AVG(NVL(B.SCORE, 0)),1)  FROM
(
    SELECT T1.SID, T1.SNAME, T2.SUBID, T2.SNAME AS SUBNAME FROM STUDENTS T1, SUBJECTS T2
) A, SCORES B
WHERE A.SID = B.SID(+) AND A.SUBID = B.SUBID(+)
GROUP BY A.SID, A.SNAME
ORDER BY A.SID
;

SELECT B.SCORE, NVL(B.SCORE, 0) FROM
(
    SELECT T1.SID, T1.SNAME, T2.SUBID, T2.SNAME AS SUBNAME FROM STUDENTS T1, SUBJECTS T2
) A, SCORES B
WHERE A.SID = B.SID(+) AND A.SUBID = B.SUBID(+)
ORDER BY A.SID

;