--5. 부산에 사는 학생들의 영어시험 평균과 총점을 리스트로 보여주세요

SELECT * FROM SCORES;
SELECT * FROM STUDENTS;
SELECT * FROM SUBJECTS;

--부산에 사는 학생들의 시험결과 리스트
SELECT  T2.SID, T2.SNAME, SUM(T1.SCORE) AS TSCORE, AVG(SCORE) AS ASCORE
FROM SCORES T1, STUDENTS T2
WHERE T1.SID = T2.SID
AND T2.SADDR = '부산'
GROUP BY T2.SID, T2.SNAME
ORDER BY SID ASC
;
SELECT *
FROM SCORES T1, STUDENTS T2
WHERE T1.SID = T2.SID
AND T2.SADDR = '부산'
AND T1.SUBID = 'S003'
;

--1.학생테이블에 부산에 사는 학생이 몇명이지 확인
SELECT COUNT(*) FROM STUDENTS
WHERE SADDR = '부산'
;

--2. 부산에 사는 학생들이 영어시험을 다 쳤을까??
SELECT * FROM STUDENTS T1, SCORES T2
WHERE T1.SID = T2.SID
AND T2.PID = 'P005' AND T2.SUBID = 'S003'
AND T1.SADDR = '부산'
;
SELECT * FROM EXAMS;


