--15. 각 교수별로 출제한 시험의 평균 점수를 보여주세요
SELECT * FROM STUDENTS;
SELECT * FROM PROFESSORS;
SELECT * FROM SUBJECTS;
SELECT * FROM EXAMS;
SELECT * FROM SCORES
WHERE PID = 'P008' AND SUBID = 'S006'
;

-- 교수가 시험을 출제 --> 리스트
SELECT *
FROM PROFESSORS T1, EXAMS T2
WHERE T1.PID = T2.PID
;


SELECT *
FROM PROFESSORS T1, EXAMS T2, SCORES T3
WHERE T1.PID = T2.PID
AND T2.PID = T3.PID AND T2.SUBID = T3.SUBID;


SELECT T1.PID, T1.PNAME, T2.SUBID, SUM(T3.SCORE), ROUND(AVG(T3.SCORE), 1)
FROM PROFESSORS T1, EXAMS T2, SCORES T3
WHERE T1.PID = T2.PID
AND T2.PID = T3.PID AND T2.SUBID = T3.SUBID
GROUP BY T1.PID, T1.PNAME, T2.SUBID
ORDER BY ROUND(AVG(T3.SCORE), 1) DESC
;

--교수아이디, 교수이름, 과목아이디, 과목이름, 평균점수, 합계


