
CREATE TABLE BOARD(
    IDX     INT             PRIMARY KEY,
    TITLE   VARCHAR2(100)   NOT NULL,
    USERID  CHAR(6)         NOT NULL,
    REGDATE DATE            NOT NULL
);

CREATE TABLE USERS(
    USERID      CHAR(6)         PRIMARY KEY,
    USERNAME    VARCHAR2(30)    NOT NULL
);


SELECT * FROM BOARD;

SELECT * FROM USERS;

