create or replace NONEDITIONABLE PACKAGE PKG_HOSPITAL AS 

  PROCEDURE PROC_INS_HOSPITAL
(
    IN_HOS_ID               IN VARCHAR2
    , IN_HOS_NAME	        IN VARCHAR2
	, IN_HOS_ADDR_GRP	    IN VARCHAR2   
	, IN_HOS_ADDR	        IN VARCHAR2		    
	, IN_HOS_ROOM_QTY	    IN VARCHAR2		    
	, IN_HOS_OPEN_DATE      IN VARCHAR2	
    , O_ERRCODE       OUT     VARCHAR2
    , O_ERRMSG        OUT     VARCHAR2  
)
;

PROCEDURE PROC_SEL_HOSPITAL
(
    IN_HOS_ID               IN VARCHAR2
    , IN_HOS_NAME	        IN VARCHAR2
	, IN_HOS_ADDR_GRP	    IN VARCHAR2   
	, IN_HOS_ADDR	        IN VARCHAR2		    
	, IN_HOS_ROOM_QTY	    IN VARCHAR2		    
	, IN_HOS_OPEN_DATE      IN VARCHAR2
    , O_CUR           OUT     SYS_REFCURSOR
    , O_ERRCODE       OUT     VARCHAR2
    , O_ERRMSG        OUT     VARCHAR2  
)
;

PROCEDURE PROC_UP_HOSPITAL
(
    IN_HOS_ID               IN VARCHAR2
    , IN_HOS_NAME	        IN VARCHAR2
	, IN_HOS_ADDR_GRP	    IN VARCHAR2   
	, IN_HOS_ADDR	        IN VARCHAR2		    
	, IN_HOS_ROOM_QTY	    IN VARCHAR2		    
	, IN_HOS_OPEN_DATE      IN VARCHAR2
    , O_ERRCODE       OUT     VARCHAR2
    , O_ERRMSG        OUT     VARCHAR2  
)
;

--DELETE
  PROCEDURE PROC_DEL_HOSPITAL
    (
        IN_HOS_ID       IN VARCHAR2
        ,O_ERRCODE      OUT VARCHAR2
        ,O_ERRMSG       OUT VARCHAR2
    )
;

END PKG_HOSPITAL;