CREATE OR REPLACE 
PACKAGE PKG_USERS AS 
--INSERT
    PROCEDURE PROC_INS_USERS
    (
        IN_USERNAME    IN  VARCHAR2
    );
--SELECT
    PROCEDURE PROC_SEL_USERS
    (
        IN_USERNAME    IN  VARCHAR2,
        O_CUR   OUT SYS_REFCURSOR
    );
--UPDATE
    PROCEDURE PROC_UP_USERS
    (
        IN_USER_ID     IN  VARCHAR2,
        IN_USERNAME    IN  VARCHAR2
    );
--DELETE
    PROCEDURE PROC_DEL_USERS
    (
        IN_USER_ID    IN  VARCHAR2
    );

END PKG_USERS;