/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-26 00:28:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boards_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Boards</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	.bRow{\r\n");
      out.write("		width:510px;\r\n");
      out.write("		height:30px;\r\n");
      out.write("		border:0px solid #777;\r\n");
      out.write("		clear:both;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.col1{\r\n");
      out.write("		width:50px;\r\n");
      out.write("		font-size:12px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		padding:8px 0px 5px 0px;\r\n");
      out.write("		border:1px solid #999;\r\n");
      out.write("		display:block;\r\n");
      out.write("		float:left;\r\n");
      out.write("	}\r\n");
      out.write("	.col2{\r\n");
      out.write("		width:80px;\r\n");
      out.write("		font-size:12px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		padding:8px 0px 5px 0px;\r\n");
      out.write("		border:1px solid #999;\r\n");
      out.write("		display:block;\r\n");
      out.write("		float:left;\r\n");
      out.write("	}\r\n");
      out.write("	.col3{\r\n");
      out.write("		width:240px;\r\n");
      out.write("		font-size:12px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		padding:8px 0px 5px 0px;\r\n");
      out.write("		border:1px solid #999;\r\n");
      out.write("		display:block;\r\n");
      out.write("		float:left;\r\n");
      out.write("	}\r\n");
      out.write("	.col4{\r\n");
      out.write("		width:130px;\r\n");
      out.write("		font-size:12px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		padding:8px 0px 5px 0px;\r\n");
      out.write("		border:1px solid #999;\r\n");
      out.write("		display:block;\r\n");
      out.write("		float:left;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body><!-- 테스트용!!! -->\r\n");
      out.write("<div>\r\n");
      out.write("	<input type=\"button\" value=\"조회\" id=\"btnSearch\" />\r\n");
      out.write("	<input type=\"button\" value=\"추가\" id=\"btnAdd\" />\r\n");
      out.write("	<input type=\"button\" value=\"저장\" id=\"btnSave\" />\r\n");
      out.write("	<input type=\"button\" value=\"삭제\" id=\"btnDelete\" />\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"board\">\r\n");
      out.write("	<div id=\"boardTitle\" class=\"bRow\">\r\n");
      out.write("		<span class=\"col1\">\r\n");
      out.write("			<input type=\"checkbox\"/>\r\n");
      out.write("		</span>\r\n");
      out.write("		<span class=\"col2\">글번호</span>\r\n");
      out.write("		<span class=\"col3\">글제목</span>\r\n");
      out.write("		<span class=\"col4\">작성자</span>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"boardRow\" class=\"bRow\">\r\n");
      out.write("		<span class=\"col1\">\r\n");
      out.write("			<input type=\"checkbox\"/>\r\n");
      out.write("		</span>\r\n");
      out.write("		<span class=\"col2\"></span>\r\n");
      out.write("		<span class=\"col3\"></span>\r\n");
      out.write("		<span class=\"col4\">\r\n");
      out.write("			<select>\r\n");
      out.write("				<option value=\"USER01\">DITTO</option>\r\n");
      out.write("				<option value=\"USER02\">MARSH</option>\r\n");
      out.write("				<option value=\"USER03\">WAN</option>\r\n");
      out.write("				<option value=\"USER04\">METAMON</option>\r\n");
      out.write("				<option value=\"USER05\">OCTO</option>\r\n");
      out.write("			</select>\r\n");
      out.write("		</span>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
