/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-02 03:18:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._01_005fadmin._01_005fboards;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Pkg.Admin.Board.BoardVO;
import java.util.ArrayList;
import Pkg.Admin.Board.BoardList;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Pkg.Admin.Board.BoardVO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("Pkg.Admin.Board.BoardList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/board.css\"/>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시판 리스트 - 관리자</title>​\r\n");
      out.write("<script>\r\n");
      out.write("	var chkAll = function(obj){\r\n");
      out.write("		var chks = document.getElementsByName(\"chk\");\r\n");
      out.write("		for(var i=0;i<chks.length;i++){\r\n");
      out.write("		if(obj.checked){\r\n");
      out.write("			chks.checked=true;\r\n");
      out.write("		}\r\n");
      out.write("		else{\r\n");
      out.write("			chks.checked=false;\r\n");
      out.write("		}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var goDelete = function(){\r\n");
      out.write("		var obj = document.getElementById(\"adminBordForm\");\r\n");
      out.write("		obj.submit();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var txtChange = function(gbn,idx){\r\n");
      out.write("		//gbn : 바뀐 값이 몇번째줄에있는지 index(글번호와다름)\r\n");
      out.write("		var gbns = document.getElementsByName(\"gbns\");\r\n");
      out.write("		gbns[gbn].value=\"U\";\r\n");
      out.write("		this.style.backgroundColor=\"red\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var addRow = function(){\r\n");
      out.write("		var oldHTML = document.getElementById(\"boards\").innerHTML;\r\n");
      out.write("		var strHTML = \"\";\r\n");
      out.write("		strHTML += '<div class=\"row\" name=\"boardRow\">';\r\n");
      out.write("		strHTML += '<span class=\"col0\">';\r\n");
      out.write("		strHTML += 		'<input type=\"checkbox\" name=\"idxs\"/>';\r\n");
      out.write("		strHTML += '</span>';\r\n");
      out.write("		strHTML += '<span class=\"col1\"> </span>';\r\n");
      out.write("		strHTML += 		'<input type=\"text\" class=\"col2\" name=\"titles\"/>';\r\n");
      out.write("		strHTML += 		'<input type=\"text\" class=\"col3\" name=\"userID\"/>';\r\n");
      out.write("		strHTML += '<span class=\"col4\"></span>';\r\n");
      out.write("		strHTML += '<span style=\"width:0px\" type=\"hidden\" name=\"gbns\" value=\"I\"></span>';\r\n");
      out.write("		strHTML += '</div><!-- boardRow -->';\r\n");
      out.write("	\r\n");
      out.write("		document.getElementById(\"boards\").innerHTML = oldHTML+strHTML;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");


	BoardList boardList = new BoardList();
	ArrayList<BoardVO> aList = boardList.getBoardList();


      out.write("\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("<form name=\"adminBordForm\" id=\"adminBordForm\" method=\"post\" action=\"./boardList_ok.jsp\">\r\n");
      out.write("		<div id=\"btns\">\r\n");
      out.write("			<div class=\"left\"></div>\r\n");
      out.write("			<div class=\"right\">\r\n");
      out.write("				<span class=\"btn\">조회</span>\r\n");
      out.write("				<span class=\"btn\" onclick=\"addRow()\">추가</span>\r\n");
      out.write("				<span class=\"btn\" name=\"update\">저장</span>\r\n");
      out.write("				<span class=\"btn\" name=\"delete\" onclick=\"goDelete()\">삭제</span>\r\n");
      out.write("			</div><!-- right -->\r\n");
      out.write("		</div><!-- btns -->\r\n");
      out.write("		\r\n");
      out.write("			<div id=\"boards\">\r\n");
      out.write("				<div class=\"row\" name=\"boardTRow\">\r\n");
      out.write("					<span class=\"col0\">\r\n");
      out.write("						<input type=\"checkbox\" name=\"chkT\" id=\"chkT\" onclick=\"chkAll(this)\"/>\r\n");
      out.write("					</span>\r\n");
      out.write("					<span class=\"col1\">번호</span>\r\n");
      out.write("					<span class=\"col2\" style=\"text-align: center\">글제목</span>\r\n");
      out.write("					<span class=\"col3\">작성자</span>\r\n");
      out.write("					<span class=\"col4\">작성일</span>\r\n");
      out.write("					<span></span>\r\n");
      out.write("				</div><!-- boardTRow -->\r\n");
      out.write("				");
	int i=0;
					for(BoardVO vo : aList){
				
      out.write("\r\n");
      out.write("				<div class=\"row\" name=\"boardRow\">\r\n");
      out.write("					<span class=\"col0\">\r\n");
      out.write("						<input type=\"checkbox\" name=\"idxs\" value=\"");
      out.print(vo.getIdx() );
      out.write("\"/>\r\n");
      out.write("					</span>\r\n");
      out.write("					<span class=\"col1\">");
      out.print(vo.getIdx() );
      out.write("</span>\r\n");
      out.write("					<input type=\"text\" class=\"col2\" name=\"titles\" \r\n");
      out.write("						value=\"");
      out.print(vo.getTitle() );
      out.write("\" onchange=\"txtchange(");
      out.print(i );
      out.write(',');
      out.print(vo.getIdx() );
      out.write(")\"/>\r\n");
      out.write("					<input type=\"text\" class=\"col3\" name=\"userID\" \r\n");
      out.write("						value=\"");
      out.print(vo.getUserID() );
      out.write("\" onchange=\"txtchange(");
      out.print(i );
      out.write(',');
      out.print(vo.getIdx() );
      out.write(")\"/>\r\n");
      out.write("					<span class=\"col4\">");
      out.print(vo.getRegdate() );
      out.write("</span>\r\n");
      out.write("					<span style=\"width:0px\" type=\"hidden\" name=\"gbns\"></span>\r\n");
      out.write("				</div><!-- boardRow -->\r\n");
      out.write("				\r\n");
      out.write("				");
		i++;
					}
				
      out.write("\r\n");
      out.write("				\r\n");
      out.write("			</div><!-- boards -->\r\n");
      out.write("	</form><!-- adminBordForm -->\r\n");
      out.write("	</div><!-- wrap -->\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
