
SELECT T1.STU_ID, T1.STU_NAME, COUNT(T1.STU_ID) AS CNT
FROM STUDENTS_TBL T1, STUDENTS_TIME_TBL T2
WHERE T1.STU_ID=T2.STU_ID
GROUP BY T1.STU_ID, T1.STU_NAME
ORDER BY T1.STU_ID;



--학과별 학생 리스트
    SELECT T2.GID1, T2.CID2, T2.FULLDEPT, T1.STU_ID, T1.STU_NAME,
        COUNT(*) AS CNT,
        RANK() OVER(PARTITION BY T2.GID1, T2.CID2 ORDER BY COUNT(*) DESC) AS RNK
    FROM STUDENTS_TBL T1,
    (
        --학과
        SELECT T2.GRP_ID AS GID1, T2.COM_ID AS CID1, 
            T2.COM_VAL AS CVAL1,
            T3.GRP_ID AS GID2, T3.COM_ID AS CID2, 
            T3.COM_VAL AS CVAL2,
            T2.COM_VAL||' '||T3.COM_VAL AS FULLDEPT
        FROM COMMONS_TBL T1, COMMONS_TBL T2, COMMONS_TBL T3
        WHERE T1.GRP_ID=T2.GRP_ID AND T1.COM_ID=T2.PARENT_ID
            AND T2.GRP_ID=T3.GRP_ID AND T2.COM_ID=T3.PARENT_ID
            AND T1.GRP_ID='GRP002' 
    ) T2, STUDENTS_TIME_TBL T3
    WHERE T1.STU_DEPT_GRP=T2.GID1 AND T1.STU_DEPT=T2.CID2 AND T1.STU_ID=T3.STU_ID
    GROUP BY T2.GID1, T2.CID2, T2.FULLDEPT, T1.STU_ID, T1.STU_NAME;

--학과
SELECT T2.GRP_ID AS GID1, T2.COM_ID AS CID1, 
    T2.COM_VAL AS CVAL1,
    T3.GRP_ID AS GID2, T3.COM_ID AS CID2, 
    T3.COM_VAL AS CVAL2,
    T2.COM_VAL||' '||T3.COM_VAL AS FULLDEPT
FROM COMMONS_TBL T1, COMMONS_TBL T2, COMMONS_TBL T3
WHERE T1.GRP_ID=T2.GRP_ID AND T1.COM_ID=T2.PARENT_ID
    AND T2.GRP_ID=T3.GRP_ID AND T2.COM_ID=T3.PARENT_ID
    AND T1.GRP_ID='GRP002' ;



--학생별 수강 리스트

SELECT B.CID2, B.FULLDEPT, A.STU_ID, A.STU_NAME,
    COUNT(*) AS CNT,
    SUM(D.SUB_CREDIT) AS TOTALCREDIT
FROM STUDENTS_TBL A,
(
    SELECT T2.GRP_ID AS GID1, T2.COM_ID AS CID1, 
        T2.COM_VAL AS CVAL1,
        T3.GRP_ID AS GID2, T3.COM_ID AS CID2, 
        T3.COM_VAL AS CVAL2,
        T2.COM_VAL||' '||T3.COM_VAL AS FULLDEPT
    FROM COMMONS_TBL T1, COMMONS_TBL T2, COMMONS_TBL T3
    WHERE T1.GRP_ID=T2.GRP_ID AND T1.COM_ID=T2.PARENT_ID
        AND T2.GRP_ID=T3.GRP_ID AND T2.COM_ID=T3.PARENT_ID
        AND T1.GRP_ID='GRP002' 
) B, STUDENTS_TIME_TBL C, SUBJECTS_TBL D
WHERE A.STU_DEPT_GRP=B.GID1 AND A.STU_DEPT=B.CID2
    AND A.STU_ID=C.STU_ID
    AND C.SUB_ID=D.SUB_ID
GROUP BY B.CID2, B.FULLDEPT, A.STU_ID, A.STU_NAME
ORDER BY A.STU_ID;



--PARTITION BY : 다른 필드와 무관하게 영역 지정해 같은 값을 출력
SELECT B.CID2, B.FULLDEPT, A.STU_ID, A.STU_NAME, D.SUB_CREDIT, D.SUB_ID, D.SUB_NAME,
    SUM(SUB_CREDIT) OVER(PARTITION BY A.STU_ID) AS TOTALCREDIT,--17학점
    SUM(DECODE(A.STU_ID,NULL,0,1)) OVER(PARTITION BY A.STU_ID)AS CNT,--6과목
    ROUND(AVG(SUB_CREDIT) OVER(PARTITION BY A.STU_ID),1) AS AVGCREDIT
FROM STUDENTS_TBL A,
(
    SELECT T2.GRP_ID AS GID1, T2.COM_ID AS CID1, 
        T2.COM_VAL AS CVAL1,
        T3.GRP_ID AS GID2, T3.COM_ID AS CID2, 
        T3.COM_VAL AS CVAL2,
        T2.COM_VAL||' '||T3.COM_VAL AS FULLDEPT
    FROM COMMONS_TBL T1, COMMONS_TBL T2, COMMONS_TBL T3
    WHERE T1.GRP_ID=T2.GRP_ID AND T1.COM_ID=T2.PARENT_ID
        AND T2.GRP_ID=T3.GRP_ID AND T2.COM_ID=T3.PARENT_ID
        AND T1.GRP_ID='GRP002' 
) B, STUDENTS_TIME_TBL C, SUBJECTS_TBL D
WHERE A.STU_DEPT_GRP=B.GID1 AND A.STU_DEPT=B.CID2
    AND A.STU_ID=C.STU_ID
    AND C.SUB_ID=D.SUB_ID
GROUP BY B.CID2, B.FULLDEPT, A.STU_ID, A.STU_NAME, D.SUB_CREDIT, D.SUB_ID, D.SUB_NAME
ORDER BY A.STU_ID;


















