CREATE OR REPLACE
PACKAGE BODY PKG_MEMBERS AS

  PROCEDURE PROC_CHK_USERID
    (
        IN_USERID   IN      VARCHAR2,
        O_CUR       OUT     SYS_REFCURSOR
    ) AS
        V_CNT   INT;
  BEGIN
    
    SELECT COUNT(*)
    INTO V_CNT
    FROM MEMBERS2
    WHERE USERID=IN_USERID
    ;
    
    --0이면 가능, 1이면 중복
    OPEN O_CUR FOR
    SELECT V_CNT AS CNT
    FROM DUAL;
    
  END PROC_CHK_USERID;

  PROCEDURE PROC_INS_USER
    (
        IN_USERID   IN  VARCHAR2,
        IN_USERPASS   IN  VARCHAR2,
        IN_USERNAME IN  VARCHAR2
    ) AS
  BEGIN
    INSERT INTO MEMBERS2(USERID, USERPASS, USERNAME)
    VALUES(IN_USERID, IN_USERPASS, IN_USERNAME)
    ;
  END PROC_INS_USER;

  PROCEDURE PROC_JOIN_USER
    (
        IN_USERID       IN  VARCHAR2,
        IN_USERPASS     IN  VARCHAR2,
        IN_USERNAME     IN  VARCHAR2,
        IN_USERGEN      IN  VARCHAR2,
        IN_USERHOBBY    IN  VARCHAR2,
        O_CUR       OUT SYS_REFCURSOR
    ) AS
        V_OK    VARCHAR2(20);
  BEGIN
    SELECT DECODE(MAX(USERID),NULL,'TRUE','FALSE')
    INTO V_OK
    FROM MEMBERS
    WHERE USERID=IN_USERID;
    
    IF V_OK='TRUE' THEN
        INSERT INTO MEMBERS(USERID, USERPASS, USERNAME, USERGEN, USERHOBBY, REGDATE)
        VALUES(IN_USERID, IN_USERPASS, IN_USERNAME, IN_USERGEN, IN_USERHOBBY, SYSDATE)
        ;
    END IF;
    
    OPEN O_CUR FOR
    SELECT V_OK FROM DUAL;
    
  END PROC_JOIN_USER;

END PKG_MEMBERS;