
--모든 사람의 의료비
-- / 이름 주민번호 나이 성별 주소코드 주소 / 진료비 / 병실비 / 약값 / 총합


--병원방문 + 진료 + 입원 + 약 + 병실 + 퇴원

--조건--
--모든 병원 방문자는 진료받음
--모든 입원한 사람은 퇴원
--모든 입원한 사람은 약을 처방받음
--모든 입원한 사람은 병실 사용



--진료받은사람
SELECT T2.PER_ID, T2.TRE_ID
FROM PATIENT_TBL T1
    , TREAT_TBL T2
WHERE T1.PAT_ID=T2.PAT_ID
;
--진료받은사람별 진료비
SELECT T2.PER_ID, SUM(T2.TRE_PAY)
FROM PATIENT_TBL T1
    , TREAT_TBL T2
WHERE T1.PAT_ID=T2.PAT_ID
GROUP BY T2.PER_ID
;


--입원한사람+입원ID
SELECT T3.PER_ID, T3.ADM_ID
FROM PATIENT_TBL T1
    , TREAT_TBL T2
    , ADMISSION_TBL T3
WHERE T1.PAT_ID=T2.PAT_ID
    AND T2.TRE_ID=T3.TRE_ID
;
--입원한사람별 진료비
SELECT T3.PER_ID
    , SUM(T2.TRE_PAY) AS ADMPER_TREPAY
FROM PATIENT_TBL T1
    , TREAT_TBL T2
    , ADMISSION_TBL T3
WHERE T1.PAT_ID=T2.PAT_ID
    AND T2.TRE_ID=T3.TRE_ID
GROUP BY T3.PER_ID
;


--입원건별 진료비
SELECT T3.ADM_ID
    , T2.TRE_PAY
FROM PATIENT_TBL T1
    , TREAT_TBL T2
    , ADMISSION_TBL T3
WHERE T1.PAT_ID=T2.PAT_ID
    AND T2.TRE_ID=T3.TRE_ID
;

--입원건별 병실비
SELECT T2.ADM_ID
    , SUM(TO_NUMBER(T1.EXP_VAL1)) AS ROOMPAY
FROM COMMONS_TBL T1
    , ADMISSION_ROOMS_TBL T2
WHERE T1.GRP_ID=T2.ADM_ROOM_GRP
    AND T1.COM_ID=T2.ADM_ROOM
GROUP BY T2.ADM_ID
;

--입원한사람별 병실비
SELECT A.PER_ID, A.PER_NAME, SUM(B.ROOMPAY) AS ADMPER_ROOMPAY
FROM
(
    --사람 + 입원
    SELECT T1.PER_NAME, T1.PER_ID, T2.ADM_ID
    FROM PERSON_TBL T1, ADMISSION_TBL T2
    WHERE T1.PER_ID=T2.PER_ID
) A,
(
    --입원건별 병실비
    SELECT T2.ADM_ID
        , SUM(TO_NUMBER(T1.EXP_VAL1)) AS ROOMPAY
    FROM COMMONS_TBL T1
        , ADMISSION_ROOMS_TBL T2
    WHERE T1.GRP_ID=T2.ADM_ROOM_GRP
        AND T1.COM_ID=T2.ADM_ROOM
    GROUP BY T2.ADM_ID
) B
WHERE A.ADM_ID=B.ADM_ID
GROUP BY A.PER_ID, A.PER_NAME
;

--입원건별 약값
SELECT T2.ADM_ID
    , SUM(TO_NUMBER(T1.EXP_VAL1)*ADM_MED_QTY) AS MEDPAY
FROM COMMONS_TBL T1
    , ADMISSION_MEDICINES_TBL T2
WHERE T1.GRP_ID=T2.ADM_MED_GRP
    AND T1.COM_ID=T2.ADM_MED
GROUP BY T2.ADM_ID
;
--입원한사람별 약값
SELECT A.PER_ID, A.PER_NAME, SUM(B.MEDPAY)
FROM
(
    --사람 + 입원
    SELECT T1.PER_NAME, T1.PER_ID, T2.ADM_ID
    FROM PERSON_TBL T1, ADMISSION_TBL T2
    WHERE T1.PER_ID=T2.PER_ID
) A,
(
    --입원건별 약값
    SELECT T2.ADM_ID
        , SUM(TO_NUMBER(T1.EXP_VAL1)*ADM_MED_QTY) AS MEDPAY
    FROM COMMONS_TBL T1
        , ADMISSION_MEDICINES_TBL T2
    WHERE T1.GRP_ID=T2.ADM_MED_GRP
        AND T1.COM_ID=T2.ADM_MED
    GROUP BY T2.ADM_ID
) B
WHERE A.ADM_ID=B.ADM_ID
GROUP BY A.PER_ID, A.PER_NAME
;

--입원건당 병실비 + 약값 + 진료비
SELECT A.ADM_ID
    , TO_CHAR(A.ROOMPAY,'FM999,999,999') AS ROOMPAY
    , TO_CHAR(B.MEDPAY,'FM999,999,999') AS MEDPAY
    , TO_CHAR(C.TRE_PAY,'FM999,999,999') AS TREPAY
    , TO_CHAR(SUM(A.ROOMPAY+B.MEDPAY+C.TRE_PAY),'FM999,999,999') AS TOTALPAY
FROM
(
    --입원건별 병실비
    SELECT T2.ADM_ID
        , SUM(TO_NUMBER(T1.EXP_VAL1)) AS ROOMPAY
    FROM COMMONS_TBL T1
        , ADMISSION_ROOMS_TBL T2
    WHERE T1.GRP_ID=T2.ADM_ROOM_GRP
        AND T1.COM_ID=T2.ADM_ROOM
    GROUP BY T2.ADM_ID
) A,
(
    --입원건별 약값
    SELECT T2.ADM_ID
        , SUM(TO_NUMBER(T1.EXP_VAL1)*ADM_MED_QTY) AS MEDPAY
    FROM COMMONS_TBL T1
        , ADMISSION_MEDICINES_TBL T2
    WHERE T1.GRP_ID=T2.ADM_MED_GRP
        AND T1.COM_ID=T2.ADM_MED
    GROUP BY T2.ADM_ID
) B,
(
    --입원건별 진료비
    SELECT T3.ADM_ID
        , T2.TRE_PAY
    FROM PATIENT_TBL T1
        , TREAT_TBL T2
        , ADMISSION_TBL T3
    WHERE T1.PAT_ID=T2.PAT_ID
        AND T2.TRE_ID=T3.TRE_ID
) C,
ADMISSION_TBL T1
WHERE T1.ADM_ID=A.ADM_ID
    AND T1.ADM_ID=B.ADM_ID
    AND T1.ADM_ID=C.ADM_ID
GROUP BY A.ADM_ID, A.ROOMPAY, B.MEDPAY, C.TRE_PAY
;

--사람 + 입원
SELECT T1.PER_NAME, T1.PER_ID, T2.ADM_ID
FROM PERSON_TBL T1, ADMISSION_TBL T2
WHERE T1.PER_ID=T2.PER_ID
;










---------------------------------------------------12번
--조건--
--모든 입원한 사람은 퇴원
--모든 입원한 사람은 약을 처방받음
--모든 입원한 사람은 병실 사용

--입원건별 의료비 + 사람이름
SELECT T1.ADM_ID
    , T1.PER_ID
    , T1.PER_NAME
    , TO_CHAR(T2.ROOMPAY,'999,999,999') AS ROOMPAY
    , TO_CHAR(T2.MEDPAY,'999,999,999') AS MEDPAY
    , TO_CHAR(T2.TRE_PAY,'999,999,999') AS TREPAY
    , TO_CHAR(T2.TOTALPAY,'999,999,999') AS TOTALPAY
FROM
(
    --사람 + 입원
    SELECT T1.PER_NAME, T1.PER_ID, T2.ADM_ID
    FROM PERSON_TBL T1, ADMISSION_TBL T2
    WHERE T1.PER_ID=T2.PER_ID
) T1,
(
    --입원건당 병실비 + 약값 + 진료비
    SELECT A.ADM_ID
        , A.ROOMPAY
        , B.MEDPAY
        , C.TRE_PAY
        , SUM(A.ROOMPAY+B.MEDPAY+C.TRE_PAY) AS TOTALPAY
    FROM
    (
        --입원건별 병실비
        SELECT T2.ADM_ID
            , SUM(TO_NUMBER(T1.EXP_VAL1)) AS ROOMPAY
        FROM COMMONS_TBL T1
            , ADMISSION_ROOMS_TBL T2
        WHERE T1.GRP_ID=T2.ADM_ROOM_GRP
            AND T1.COM_ID=T2.ADM_ROOM
        GROUP BY T2.ADM_ID
    ) A,
    (
        --입원건별 약값
        SELECT T2.ADM_ID
            , SUM(TO_NUMBER(T1.EXP_VAL1)*ADM_MED_QTY) AS MEDPAY
        FROM COMMONS_TBL T1
            , ADMISSION_MEDICINES_TBL T2
        WHERE T1.GRP_ID=T2.ADM_MED_GRP
            AND T1.COM_ID=T2.ADM_MED
        GROUP BY T2.ADM_ID
    ) B,
    (
        --입원건별 진료비
        SELECT T3.ADM_ID
            , T2.TRE_PAY
        FROM PATIENT_TBL T1
            , TREAT_TBL T2
            , ADMISSION_TBL T3
        WHERE T1.PAT_ID=T2.PAT_ID
            AND T2.TRE_ID=T3.TRE_ID
    ) C,
    ADMISSION_TBL T1
    WHERE T1.ADM_ID=A.ADM_ID
        AND T1.ADM_ID=B.ADM_ID
        AND T1.ADM_ID=C.ADM_ID
    GROUP BY A.ADM_ID, A.ROOMPAY, B.MEDPAY, C.TRE_PAY
) T2, DISCHARGE_TBL T3
WHERE T1.ADM_ID=T2.ADM_ID
    AND T1.ADM_ID=T3.ADM_ID
ORDER BY T1.ADM_ID ASC
;





--모든사람의 의료비?
--사람 + 진료 + 입원자는 병실+약값

SELECT T1.PER_ID
    , T1.PER_NAME
    , NVL(T2.TREPER_TREPAY,0) AS TREPER_TREPAY
    , NVL(T5.ADMPER_TREPAY,0) AS ADMPER_TREPAY
    , NVL(T3.ADMPER_ROOMPAY,0) AS ADMPER_ROOMPAY
    , NVL(T4.ADMPER_MEDPAY,0) AS ADMPER_MEDPAY
FROM PERSON_TBL T1,
(
    --진료받은사람별 진료비
    SELECT T2.PER_ID, SUM(T2.TRE_PAY) AS TREPER_TREPAY
    FROM PATIENT_TBL T1
        , TREAT_TBL T2
    WHERE T1.PAT_ID=T2.PAT_ID
    GROUP BY T2.PER_ID
) T2,
(
    --입원한사람별 병실비
    SELECT A.PER_ID, A.PER_NAME, SUM(B.ROOMPAY) AS ADMPER_ROOMPAY
    FROM
    (
        --사람 + 입원
        SELECT T1.PER_NAME, T1.PER_ID, T2.ADM_ID
        FROM PERSON_TBL T1, ADMISSION_TBL T2
        WHERE T1.PER_ID=T2.PER_ID
    ) A,
    (
        --입원건별 병실비
        SELECT T2.ADM_ID
            , SUM(TO_NUMBER(T1.EXP_VAL1)) AS ROOMPAY
        FROM COMMONS_TBL T1
            , ADMISSION_ROOMS_TBL T2
        WHERE T1.GRP_ID=T2.ADM_ROOM_GRP
            AND T1.COM_ID=T2.ADM_ROOM
        GROUP BY T2.ADM_ID
    ) B
    WHERE A.ADM_ID=B.ADM_ID
    GROUP BY A.PER_ID, A.PER_NAME
) T3,
(
    --입원한사람별 약값
    SELECT A.PER_ID, A.PER_NAME, SUM(B.MEDPAY) AS ADMPER_MEDPAY
    FROM
    (
        --사람 + 입원
        SELECT T1.PER_NAME, T1.PER_ID, T2.ADM_ID
        FROM PERSON_TBL T1, ADMISSION_TBL T2
        WHERE T1.PER_ID=T2.PER_ID
    ) A,
    (
        --입원건별 약값
        SELECT T2.ADM_ID
            , SUM(TO_NUMBER(T1.EXP_VAL1)*ADM_MED_QTY) AS MEDPAY
        FROM COMMONS_TBL T1
            , ADMISSION_MEDICINES_TBL T2
        WHERE T1.GRP_ID=T2.ADM_MED_GRP
            AND T1.COM_ID=T2.ADM_MED
        GROUP BY T2.ADM_ID
    ) B
    WHERE A.ADM_ID=B.ADM_ID
    GROUP BY A.PER_ID, A.PER_NAME
) T4,
(
    --입원자별 진료비
    SELECT T3.PER_ID
        , SUM(T2.TRE_PAY) AS ADMPER_TREPAY
    FROM PATIENT_TBL T1
        , TREAT_TBL T2
        , ADMISSION_TBL T3
    WHERE T1.PAT_ID=T2.PAT_ID
        AND T2.TRE_ID=T3.TRE_ID
    GROUP BY T3.PER_ID
) T5
WHERE T1.PER_ID=T2.PER_ID(+)
    AND T1.PER_ID=T3.PER_ID(+)
    AND T1.PER_ID=T4.PER_ID(+)
    AND T1.PER_ID=T5.PER_ID(+)
ORDER BY PER_NAME ASC
;





