CREATE OR REPLACE PROCEDURE PROC_TYPE_TEST2 
(
    O_RESULT    OUT VARCHAR2
)
AS 
    --선언된 프로시져에서만 사용 가능한 지역변수
    TYPE ARR_TYPE2 IS VARRAY(3) OF VARCHAR2(30);
    
    V_ARR_TYPE  ARR_TYPE2;

BEGIN

    V_ARR_TYPE := ARR_TYPE2('KIM','LEE','PARK');
    
    FOR I IN 1..3
    LOOP
        DBMS_OUTPUT.PUT_LINE(V_ARR_TYPE(I));
    END LOOP;

END PROC_TYPE_TEST2;